@extends('layouts.admin')
@section('header', 'CatBoost Learner Support')
@section('content')
<div class="space-y-6">
    <div class="flex flex-wrap justify-between gap-3"><div><h1 class="text-2xl font-bold">CatBoost learner-support centre</h1><p class="text-sm text-gray-500">Local runtime: {{ ($health = $risk->health())['status'] ?? 'unavailable' }} · Model {{ !empty($health['model_ready']) ? 'ready' : 'not trained' }}</p></div><div class="flex flex-wrap gap-2"><form method="POST" action="{{ route('admin.risk.train') }}">@csrf<button class="rounded border px-4 py-2 text-sm font-semibold">Train local CatBoost</button></form><form method="POST" action="{{ route('admin.risk.recompute') }}">@csrf<button class="rounded bg-violet-700 px-4 py-2 text-sm font-semibold text-white">Compute school results</button></form><form method="POST" action="{{ route('admin.risk.email-schools') }}">@csrf<button class="rounded bg-green-700 px-4 py-2 text-sm font-semibold text-white">Email eligible schools</button></form></div></div>
    <section class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950"><strong>Real training data:</strong> CatBoost reads historical attendance, approved exam results, fee balances and enrolment data already stored for every active school. It trains only from anonymised numeric feature rows; the table below shows exactly how much usable data each school contributes. It needs at least 30 samples and both learner-support outcomes before training can succeed. Plan access controls prediction visibility, not whether a school’s anonymised historical data contributes to training.</section>
    @if(session('success'))<div class="rounded bg-green-50 p-3 text-green-800">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="rounded bg-red-50 p-3 text-red-800">{{ session('error') }}</div>@endif
    <section class="overflow-x-auto rounded-xl bg-white shadow"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th class="p-3">School</th><th class="p-3">Plan access</th><th class="p-3">Learners</th><th class="p-3">Training samples</th><th class="p-3">Risk / stable labels</th><th class="p-3">Current predictions</th></tr></thead><tbody class="divide-y">@forelse($trainingReadiness as $row)<tr><td class="p-3 font-semibold">{{ $row['school']->name }}</td><td class="p-3"><span class="rounded-full px-2 py-1 text-xs {{ $row['eligible'] ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-700' }}">{{ $row['eligible'] ? 'Eligible' : 'Plan not enabled' }}</span></td><td class="p-3">{{ number_format($row['school']->learners_count) }}</td><td class="p-3">{{ number_format($row['samples']) }}</td><td class="p-3">{{ number_format($row['risk_examples']) }} / {{ number_format($row['stable_examples']) }}</td><td class="p-3">{{ number_format($row['predictions']) }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-gray-500">No schools are registered.</td></tr>@endforelse</tbody></table></section>
</div>
@endsection
