<div>
    <div class="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-bold text-gray-900">Classes and teacher allocations</h2><p class="text-sm text-gray-500">Assign each teacher to the exact class and learning area they manage.</p></div><div class="flex gap-2"><button wire:click="createClass" class="rounded-lg border border-green-700 px-4 py-2 text-sm font-medium text-green-700">New class</button><button wire:click="openAllocation" class="rounded-lg bg-green-700 px-4 py-2 text-sm font-medium text-white">Allocate teacher</button></div></div>
    @if($notice)<div class="mb-4 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">{{ $notice }}</div>@endif
    <div class="mb-5 flex gap-2 border-b"><button wire:click="$set('tab','classes')" class="border-b-2 px-4 py-2 text-sm {{ $tab === 'classes' ? 'border-green-700 text-green-700' : 'border-transparent text-gray-500' }}">Classes</button><button wire:click="$set('tab','allocations')" class="border-b-2 px-4 py-2 text-sm {{ $tab === 'allocations' ? 'border-green-700 text-green-700' : 'border-transparent text-gray-500' }}">Teacher allocations</button></div>
    @if($tab === 'classes')
    <div class="overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left text-xs uppercase">Class</th><th class="px-4 py-3 text-left text-xs uppercase">Grade</th><th class="px-4 py-3 text-left text-xs uppercase">Class teacher</th><th class="px-4 py-3 text-left text-xs uppercase">Year</th><th></th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($classes as $class)<tr><td class="px-4 py-3 text-sm font-semibold">{{ $class->name }}</td><td class="px-4 py-3 text-sm">{{ $class->grade_level }}</td><td class="px-4 py-3 text-sm">{{ $class->classTeacher?->full_name ?: 'Not assigned' }}</td><td class="px-4 py-3 text-sm">{{ $class->academic_year }}</td><td class="px-4 py-3 text-right"><button wire:click="editClass({{ $class->id }})" class="text-sm text-green-700">Edit</button></td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-sm text-gray-400">No classes created.</td></tr>@endforelse</tbody></table></div>
    @else
    <div class="overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left text-xs uppercase">Teacher</th><th class="px-4 py-3 text-left text-xs uppercase">Subject</th><th class="px-4 py-3 text-left text-xs uppercase">Class</th><th class="px-4 py-3 text-left text-xs uppercase">Term/year</th><th></th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($allocations as $allocation)<tr><td class="px-4 py-3 text-sm">{{ $allocation->teacher->full_name }}</td><td class="px-4 py-3 text-sm">{{ $allocation->learningArea->name }}</td><td class="px-4 py-3 text-sm">{{ $allocation->schoolClass->name }}</td><td class="px-4 py-3 text-sm">Term {{ $allocation->term }} / {{ $allocation->academic_year }}</td><td class="px-4 py-3 text-right"><button wire:click="removeAllocation({{ $allocation->id }})" class="text-sm text-red-600">Remove</button></td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-sm text-gray-400">No allocations created.</td></tr>@endforelse</tbody></table></div>
    @endif
    @if($showClassForm)<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div class="w-full max-w-xl rounded-xl bg-white p-6"><h3 class="mb-4 text-lg font-bold">{{ $editingClassId ? 'Edit class' : 'New class' }}</h3><div class="grid grid-cols-1 gap-3 md:grid-cols-2"><input wire:model="classForm.name" placeholder="Class name e.g. Grade 5 East" class="rounded-lg border px-3 py-2 text-sm"><select wire:model="classForm.grade_level" class="rounded-lg border px-3 py-2 text-sm"><option value="">Grade</option>@foreach($grades as $grade)<option value="{{ $grade }}">{{ $grade }}</option>@endforeach</select><input wire:model="classForm.stream" placeholder="Stream (optional)" class="rounded-lg border px-3 py-2 text-sm"><input wire:model="classForm.capacity" type="number" min="1" placeholder="Capacity" class="rounded-lg border px-3 py-2 text-sm"><select wire:model="classForm.class_teacher_id" class="rounded-lg border px-3 py-2 text-sm md:col-span-2"><option value="">Class teacher (optional)</option>@foreach($staff as $member)<option value="{{ $member->id }}">{{ $member->full_name }}</option>@endforeach</select></div><div class="mt-5 flex justify-end gap-2"><button wire:click="$set('showClassForm', false)" class="rounded-lg border px-4 py-2 text-sm">Cancel</button><button wire:click="saveClass" class="rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white">Save class</button></div></div></div>@endif
    @if($showAllocationForm)<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div class="w-full max-w-xl rounded-xl bg-white p-6"><h3 class="mb-4 text-lg font-bold">Allocate teacher</h3><div class="grid grid-cols-1 gap-3"><select wire:model="allocationForm.teacher_id" class="rounded-lg border px-3 py-2 text-sm"><option value="">Teacher</option>@foreach($staff as $member)<option value="{{ $member->id }}">{{ $member->full_name }}</option>@endforeach</select><select wire:model="allocationForm.learning_area_id" class="rounded-lg border px-3 py-2 text-sm"><option value="">Learning area</option>@foreach($learningAreas as $area)<option value="{{ $area->id }}">{{ $area->name }}</option>@endforeach</select><select wire:model="allocationForm.class_id" class="rounded-lg border px-3 py-2 text-sm"><option value="">Class</option>@foreach($classes as $class)<option value="{{ $class->id }}">{{ $class->name }}</option>@endforeach</select><select wire:model="allocationForm.term" class="rounded-lg border px-3 py-2 text-sm">@foreach([1,2,3] as $term)<option value="{{ $term }}">Term {{ $term }}</option>@endforeach</select></div><div class="mt-5 flex justify-end gap-2"><button wire:click="$set('showAllocationForm', false)" class="rounded-lg border px-4 py-2 text-sm">Cancel</button><button wire:click="saveAllocation" class="rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white">Save allocation</button></div></div></div>@endif
</div>
