<div class="space-y-6">
    <div><h2 class="text-2xl font-bold text-gray-900">Academic years and terms</h2><p class="text-sm text-gray-500">Create school years, define their three terms, and activate the period used by classes, exams, reports, and fees.</p></div>
    @if($notice)<div class="rounded-lg bg-green-50 p-3 text-sm text-green-800">{{ $notice }}</div>@endif
    <section class="rounded-xl bg-white p-6 shadow-sm">
        <h3 class="mb-4 font-bold">{{ $editingId ? 'Edit academic year' : 'Create academic year' }}</h3>
        <div class="grid grid-cols-1 gap-3 md:grid-cols-3"><input wire:model="year" type="number" min="2000" max="2200" placeholder="Year" class="rounded-lg border px-3 py-2 text-sm"><input wire:model="startsOn" type="date" class="rounded-lg border px-3 py-2 text-sm"><input wire:model="endsOn" type="date" class="rounded-lg border px-3 py-2 text-sm"></div>
        <div class="mt-5 grid grid-cols-1 gap-4 md:grid-cols-3">@foreach([1,2,3] as $number)<div class="rounded-lg border p-3"><p class="mb-2 text-sm font-semibold">Term {{ $number }}</p><input wire:model="terms.{{ $number }}.name" placeholder="Term name" class="mb-2 w-full rounded-lg border px-3 py-2 text-sm"><input wire:model="terms.{{ $number }}.starts_on" type="date" class="mb-2 w-full rounded-lg border px-3 py-2 text-sm"><input wire:model="terms.{{ $number }}.ends_on" type="date" class="w-full rounded-lg border px-3 py-2 text-sm"></div>@endforeach</div>
        @error('year')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror
        <div class="mt-5 flex gap-2"><button wire:click="save" wire:loading.attr="disabled" class="rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white">Save year</button><button wire:click="resetForm" class="rounded-lg border px-4 py-2 text-sm">Clear</button></div>
    </section>
    <section class="overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left text-xs uppercase">Year</th><th class="px-4 py-3 text-left text-xs uppercase">Terms</th><th class="px-4 py-3 text-left text-xs uppercase">Status</th><th class="px-4 py-3 text-right text-xs uppercase">Actions</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($academicYears as $academicYear)<tr><td class="px-4 py-3 font-semibold">{{ $academicYear->year }}</td><td class="px-4 py-3"><div class="flex flex-wrap gap-2">@foreach($academicYear->terms as $term)<button wire:click="activateTerm({{ $term->id }})" class="rounded-full px-2 py-1 text-xs {{ $term->is_active ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-700' }}">{{ $term->name }}</button>@endforeach</div></td><td class="px-4 py-3 text-sm">{{ $academicYear->is_active ? 'Active year' : 'Inactive' }}</td><td class="px-4 py-3 text-right"><button wire:click="edit({{ $academicYear->id }})" class="mr-3 text-sm text-blue-700">Edit</button>@unless($academicYear->is_active)<button wire:click="activateYear({{ $academicYear->id }})" class="text-sm text-green-700">Activate</button>@endunless</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-sm text-gray-500">No academic years created.</td></tr>@endforelse</tbody></table></section>
</div>
