<div class="mx-auto max-w-6xl space-y-6">
    <div class="flex flex-wrap items-start justify-between gap-4">
        <div><h2 class="text-2xl font-bold text-gray-900">Backups</h2><p class="text-sm text-gray-500">Compressed database backups are uploaded to the connected Google Drive connector.</p></div>
        <button wire:click="runBackup" wire:loading.attr="disabled" wire:target="runBackup" class="rounded-lg bg-green-700 px-4 py-2 font-semibold text-white disabled:opacity-60"><span wire:loading.remove wire:target="runBackup">Run backup now</span><span wire:loading wire:target="runBackup">Backing up...</span></button>
    </div>
    @if($notice)<div class="whitespace-pre-wrap rounded-lg border border-green-200 bg-green-50 p-4 text-sm text-green-800">{{ $notice }}</div>@endif
    @if($error)<div class="whitespace-pre-wrap rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ $error }}</div>@endif
    <div class="rounded-xl bg-white p-5 shadow-sm"><p class="text-sm text-gray-600">The scheduled backup runs daily at <strong>{{ config('app.timezone') }} 02:00</strong>. It contains all database tables, including learners, classes, staff, exams, marks, finance, settings, permissions, and audit records.</p></div>
    <div class="overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full divide-y text-left text-sm"><thead class="bg-gray-50 text-xs uppercase tracking-wide text-gray-500"><tr><th class="px-4 py-3">Created</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Database</th><th class="px-4 py-3">Archive</th><th class="px-4 py-3">Drive reference</th><th class="px-4 py-3">Error</th></tr></thead><tbody class="divide-y">@forelse($backups as $backup)<tr><td class="whitespace-nowrap px-4 py-3">{{ $backup->created_at?->format('d M Y H:i:s') }}</td><td class="px-4 py-3"><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $backup->status === 'completed' ? 'bg-green-100 text-green-700' : ($backup->status === 'failed' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700') }}">{{ ucfirst($backup->status) }}</span></td><td class="px-4 py-3">{{ number_format($backup->database_size_bytes / 1024 / 1024, 2) }} MB</td><td class="px-4 py-3">{{ $backup->archive_size_bytes ? number_format($backup->archive_size_bytes / 1024 / 1024, 2).' MB' : '—' }}</td><td class="max-w-xs break-all px-4 py-3 text-xs text-gray-500">{{ $backup->drive_file_id ?: '—' }}</td><td class="max-w-sm px-4 py-3 text-xs text-red-700">{{ $backup->error ?: '—' }}</td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-gray-500">No backup runs have been recorded yet.</td></tr>@endforelse</tbody></table><div class="border-t bg-gray-50 px-4 py-3">{{ $backups->links() }}</div></div>
</div>
