<div>
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div><h2 class="text-2xl font-bold text-gray-900">Exam timetable generator</h2><p class="text-sm text-gray-500">Schedule every subject in one grouped exam by class, with collision checks.</p></div>
        <div class="flex flex-wrap gap-2"><input wire:model="academicYear" class="w-28 rounded-lg border px-3 py-2 text-sm" aria-label="Academic year"><select wire:model="term" class="rounded-lg border px-3 py-2 text-sm"><option value="1">Term 1</option><option value="2">Term 2</option><option value="3">Term 3</option></select><select wire:model.live="classId" class="rounded-lg border px-3 py-2 text-sm" aria-label="Class"><option value="">All classes</option>@foreach($classes as $class)<option value="{{ $class->id }}">{{ $class->grade_level }}{{ $class->name !== $class->grade_level ? ' - '.$class->name : '' }}</option>@endforeach</select><button wire:click="generate" wire:loading.attr="disabled" class="rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Generate timetable</button><button wire:click="publish" wire:loading.attr="disabled" class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Publish</button><button wire:click="unpublish" class="rounded-lg border px-4 py-2 text-sm">Unpublish</button><button type="button" onclick="window.print()" class="rounded-lg border px-4 py-2 text-sm">Print / Export PDF</button></div>
    </div>
    <div class="mb-5 grid gap-4 rounded-xl bg-white p-4 shadow-sm md:grid-cols-2"><label class="text-sm text-gray-700">Class<select wire:model.live="classId" class="mt-1 w-full rounded-lg border px-3 py-2"><option value="">All classes</option>@foreach($classes as $class)<option value="{{ $class->id }}">{{ $class->grade_level }}{{ $class->name !== $class->grade_level ? ' - '.$class->name : '' }}</option>@endforeach</select></label><label class="text-sm text-gray-700">Exam<select wire:model="examGroupId" class="mt-1 w-full rounded-lg border px-3 py-2"><option value="">Select grouped exam</option>@foreach($groups as $group)<option value="{{ $group->id }}">{{ $group->schoolClass?->name }} - {{ $group->name }} ({{ collect([$group->learningArea])->merge($group->groupedSubjects->pluck('learningArea'))->filter()->pluck('name')->unique()->count() }} subjects)</option>@endforeach</select></label><label class="text-sm text-gray-700">First exam date<input wire:model="startDate" type="date" class="mt-1 w-full rounded-lg border px-3 py-2"></label></div>
    @if($notice)<div class="mb-4 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">{{ $notice }}</div>@endif
    @error('examGroupId')<div class="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{{ $message }}</div>@enderror
    @error('startDate')<div class="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{{ $message }}</div>@enderror
    <div class="overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-3 py-3 text-left text-xs uppercase">Date</th><th class="px-3 py-3 text-left text-xs uppercase">Time</th><th class="px-3 py-3 text-left text-xs uppercase">Exam</th><th class="px-3 py-3 text-left text-xs uppercase">Class</th><th class="px-3 py-3 text-left text-xs uppercase">Subject</th><th class="px-3 py-3 text-left text-xs uppercase">Invigilator</th><th class="px-3 py-3 text-left text-xs uppercase">Venue</th><th class="px-3 py-3 text-left text-xs uppercase">Status</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($slots as $slot)<tr><td class="px-3 py-2 text-sm">{{ $slot->date?->format('d M Y') }}</td><td class="px-3 py-2 text-sm">{{ substr($slot->start_time, 0, 5) }} - {{ substr($slot->end_time, 0, 5) }}</td><td class="px-3 py-2 text-sm font-medium">{{ $slot->exam?->name }}</td><td class="px-3 py-2 text-sm">{{ $slot->schoolClass?->name }}</td><td class="px-3 py-2 text-sm">{{ $slot->exam?->learningArea?->name }}</td><td class="px-3 py-2 text-sm">{{ $slot->invigilator?->full_name }}</td><td class="px-3 py-2 text-sm">{{ $slot->venue }}</td><td class="px-3 py-2 text-sm">{{ $slot->is_published ? 'Published' : 'Draft' }}</td></tr>@empty<tr><td colspan="8" class="p-10 text-center text-sm text-gray-500">No exam timetable generated for this term.</td></tr>@endforelse</tbody></table></div>
</div>
