<div class="mx-auto max-w-7xl space-y-6">
    <div><h2 class="text-2xl font-bold text-gray-900">Grade Management</h2><p class="text-sm text-gray-500">Create grading scales and allocate one to each class for {{ config('school.academic_year') }}.</p></div>
    @if($saved)<div class="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{{ $saved }}</div>@endif
    <div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.35fr)]">
        <section class="rounded-xl bg-white p-6 shadow-sm">
            <div class="mb-4 flex items-center justify-between"><h3 class="font-bold text-gray-900">{{ $editingId ? 'Edit grade scale' : 'Create grade scale' }}</h3>@if($editingId)<button wire:click="resetForm" class="text-xs text-gray-500 hover:underline">New scale</button>@endif</div>
            <form wire:submit="save" class="space-y-4">
                <label class="block text-sm text-gray-700">Scale name<input wire:model="name" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" placeholder="e.g. Grade 1 CBC Scale">@error('name')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
                <label class="block text-sm text-gray-700">Description<textarea wire:model="description" rows="2" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" placeholder="When this scale should be used"></textarea></label>
                <label class="block text-sm text-gray-700">Scale type<select wire:model="type" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2"><option value="letter">Letter / numeric bands</option><option value="rubric">CBC rubric bands</option></select></label>
                <label class="block text-sm text-gray-700">Grade bands <span class="font-normal text-gray-500">(CODE|MIN|MAX|LABEL, one per line)</span><textarea wire:model="bandsText" rows="7" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 font-mono text-sm"></textarea>@error('bandsText')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
                <div><p class="mb-2 text-sm font-semibold text-gray-700">Allocate to classes for {{ config('school.academic_year') }}</p><div class="max-h-48 space-y-2 overflow-y-auto rounded-lg border border-gray-200 p-3">@forelse($classes as $class)<label class="flex items-center gap-2 text-sm text-gray-700"><input type="checkbox" wire:model="classIds" value="{{ $class->id }}" class="rounded border-gray-300 text-green-700"><span>{{ $class->grade_level }}{{ $class->name !== $class->grade_level ? ' - '.$class->name : '' }}</span></label>@empty<span class="text-sm text-gray-500">Create a class first.</span>@endforelse</div></div>
                <button type="submit" wire:loading.attr="disabled" class="w-full rounded-lg bg-green-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-green-800 disabled:opacity-60"><span wire:loading.remove wire:target="save">Save and allocate</span><span wire:loading wire:target="save">Saving...</span></button>
            </form>
        </section>
        <section class="rounded-xl bg-white p-6 shadow-sm"><div class="mb-4"><h3 class="font-bold text-gray-900">Saved grade scales</h3><p class="text-sm text-gray-500">A class can have one active scale per academic year.</p></div><div class="space-y-4">@forelse($scales as $scale)<article class="rounded-lg border border-gray-200 p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><h4 class="font-semibold text-gray-900">{{ $scale->name }}</h4><p class="text-xs uppercase tracking-wide text-gray-500">{{ $scale->type }} scale</p></div><div class="flex gap-3 text-sm"><button wire:click="edit({{ $scale->id }})" class="text-green-700 hover:underline">Edit</button><button wire:click="delete({{ $scale->id }})" wire:confirm="Delete this grade scale?" class="text-red-600 hover:underline">Delete</button></div></div><div class="mt-3 flex flex-wrap gap-2">@foreach($scale->bands ?? [] as $band)<span class="rounded bg-gray-100 px-2 py-1 text-xs text-gray-700"><strong>{{ $band['code'] }}</strong> {{ $band['min'] }}-{{ $band['max'] }}</span>@endforeach</div><p class="mt-3 text-xs text-gray-500">Classes: {{ $scale->classes->pluck('name')->join(', ') ?: 'Not allocated' }}</p></article>@empty<div class="rounded-lg border border-dashed border-gray-300 p-8 text-center text-sm text-gray-500">No grade scales created yet.</div>@endforelse</div></section>
    </div>
</div>
