<div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
        <div><h2 class="text-2xl font-bold text-gray-900">Report Forms</h2><p class="text-sm text-gray-500">Preview the three report-card designs and choose the default for official reports.</p></div>
        <button wire:click="save" wire:loading.attr="disabled" class="rounded-lg bg-green-700 px-5 py-2.5 text-sm font-semibold text-white hover:bg-green-800 disabled:opacity-60">Save as default</button>
    </div>
    @if($saved)<div class="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{{ $saved }}</div>@endif
    <div class="grid gap-6 xl:grid-cols-3">
        @foreach($templates as $key => $template)
            <button type="button" wire:click="choose('{{ $key }}')" class="rounded-xl border-2 bg-white p-4 text-left shadow-sm transition hover:shadow-md {{ $selected === $key ? 'border-green-600 ring-2 ring-green-100' : 'border-gray-200' }}">
                <div class="mb-3 flex items-center justify-between"><h3 class="font-bold text-gray-900">{{ $template['name'] }}</h3>@if($selected === $key)<span class="rounded-full bg-green-100 px-2 py-1 text-xs font-semibold text-green-700">Selected</span>@endif</div>
                <div class="report-preview {{ $key }}"><div class="report-preview-heading">{{ config('school.name') }}</div><div class="report-preview-title">SCHOOL REPORT CARD</div><div class="report-preview-meta">SCHOOL ................ GRADE ........ TERM ........</div><div class="report-preview-meta">NAME OF LEARNER ................................</div><table><thead><tr><th>LEARNING AREA</th><th>{{ $key === 'cbc-classic' ? 'CRITERIA BASED ON EXPECTED OUTCOMES' : 'PERFORMANCE' }}</th><th>{{ $key === 'cbc-compact' ? 'SIGN' : 'NARRATIVE / COMMENTS' }}</th></tr></thead><tbody><tr><td>English Activities</td><td>ME</td><td>{{ $key === 'cbc-compact' ? '___' : 'Doing well' }}</td></tr><tr><td>Mathematics Activities</td><td>EE</td><td>{{ $key === 'cbc-compact' ? '___' : 'Keep it up' }}</td></tr><tr><td>Communication and Collaboration</td><td>ME</td><td>___</td></tr></tbody></table><div class="report-preview-footer">CORE COMPETENCIES, VALUES AND P.C.I. | Teacher / Headteacher signature</div></div>
                <p class="mt-3 text-xs leading-5 text-gray-500">{{ $template['description'] }}</p>
            </button>
        @endforeach
    </div>
    <div class="rounded-xl bg-white p-6 shadow-sm"><h3 class="font-bold text-gray-900">Selected form preview</h3><p class="mt-1 text-sm text-gray-500">This is the form used when report cards are generated.</p><div class="mt-5 overflow-x-auto rounded-lg border border-gray-300 bg-gray-50 p-4"><div class="mx-auto max-w-3xl bg-white p-6 shadow-sm"><div class="text-center text-lg font-bold text-green-800">{{ config('school.name') }}</div><div class="mt-1 text-center text-sm font-bold uppercase tracking-wide text-gray-700">School Report Card</div><div class="mt-4 grid grid-cols-3 border border-gray-700 text-xs"><div class="border-r p-2">School: __________</div><div class="border-r p-2">Grade: ______</div><div class="p-2">Term: ______</div></div><div class="border-x border-b border-gray-700 p-2 text-xs">Name of learner: _________________________________________________</div><table class="mt-4 w-full border-collapse text-xs"><thead><tr class="bg-green-50"><th class="border border-gray-700 p-2">Learning Area</th><th class="border border-gray-700 p-2">Criteria Based on Expected Outcomes</th><th class="border border-gray-700 p-2">Narrative / Comments</th><th class="border border-gray-700 p-2">Sign</th></tr></thead><tbody>@foreach(['English Activities','Kiswahili Activities','Literacy Activities','Mathematics Activities','Hygiene and Nutrition Activities','Environmental Activities','Movement and Creative Activities/Music','Religious Activities (CRE and IRE)'] as $area)<tr><td class="border border-gray-700 p-2">{{ $area }}</td><td class="border border-gray-700 p-2">EE / ME / AE / BE</td><td class="border border-gray-700 p-2">________________</td><td class="border border-gray-700 p-2">___</td></tr>@endforeach</tbody></table><div class="mt-3 border border-red-700 p-2 text-xs font-bold text-red-700">CORE COMPETENCIES, VALUES AND P.C.I.</div><div class="grid grid-cols-3 border-x border-b border-gray-700 text-xs"><div class="border-r p-2 font-semibold">Communication and Collaboration<br><br>Digital Literacy<br><br>Self-Efficacy</div><div class="border-r p-2">COMMENTS<br><br><br><br><br></div><div class="p-2">SIGN<br><br><br><br><br></div></div><div class="mt-5 grid grid-cols-3 gap-4 text-xs"><div class="border-t border-gray-700 pt-2">Class Teacher</div><div class="border-t border-gray-700 pt-2">Headteacher</div><div class="border-t border-gray-700 pt-2">Parent / Guardian</div></div></div></div></div>
</div>
<style>.report-preview{border:1px solid #9ca3af;background:#fff;padding:10px;min-height:245px;color:#374151;font-size:7px}.report-preview-heading{text-align:center;font-weight:700;color:#166534;font-size:10px}.report-preview-title{text-align:center;margin:5px 0;font-weight:700}.report-preview-meta{border-bottom:1px dotted #6b7280;padding:3px 0}.report-preview table{width:100%;border-collapse:collapse;margin-top:8px}.report-preview th,.report-preview td{border:1px solid #6b7280;padding:4px;vertical-align:top}.report-preview th{color:#b91c1c;font-size:6px}.report-preview-footer{border:1px solid #b91c1c;color:#b91c1c;font-weight:700;padding:4px;margin-top:8px}.report-preview.cbc-modern{border-top:5px solid #166534}.report-preview.cbc-compact{font-size:6px;padding:7px}.report-preview.cbc-compact th,.report-preview.cbc-compact td{padding:3px}.report-preview.cbc-compact .report-preview-footer{margin-top:5px}</style>
