<div>
    <div class="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-bold text-gray-900">Subject catalog</h2><p class="text-sm text-gray-500">Manage learning areas offered by the school.</p></div><button wire:click="create" class="rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white">Add subject</button></div>
    @if(session('success'))<div class="mb-4 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">{{ session('success') }}</div>@endif
    <div class="mb-6 rounded-xl bg-white p-5 shadow-sm">
        <div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h3 class="font-semibold text-gray-900">Subjects by class</h3><p class="text-sm text-gray-500">Each class has its own active subject list. Remove unwanted subjects or add one to a class.</p></div><button wire:click="openAssignment" class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Assign subject to class</button></div>
        <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            @foreach($classes as $class)
                <div class="rounded-lg border border-gray-200 p-4"><div class="mb-3 flex items-start justify-between"><div><p class="font-semibold text-gray-900">{{ $class->name }}</p><p class="text-xs text-gray-500">{{ $class->grade_level }}</p></div><button wire:click="openAssignment({{ $class->id }})" class="text-xs font-semibold text-blue-700">Add</button></div><div class="flex flex-wrap gap-2">@forelse($class->learningAreas as $area)<span class="inline-flex items-center gap-1 rounded-full bg-green-50 px-2 py-1 text-xs text-green-800">{{ $area->name }}<button wire:click="removeFromClass({{ $class->id }}, {{ $area->id }})" class="font-bold text-red-500" title="Remove">&times;</button></span>@empty<span class="text-xs text-gray-400">No subjects assigned</span>@endforelse</div></div>
            @endforeach
        </div>
    </div>
    <div class="overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left text-xs uppercase">Name</th><th class="px-4 py-3 text-left text-xs uppercase">Code</th><th class="px-4 py-3 text-left text-xs uppercase">Grade</th><th class="px-4 py-3 text-left text-xs uppercase">Lessons/week</th><th class="px-4 py-3 text-left text-xs uppercase">Status</th><th></th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($subjects as $subject)<tr><td class="px-4 py-3 text-sm font-semibold">{{ $subject->name }}</td><td class="px-4 py-3 text-sm">{{ $subject->code }}</td><td class="px-4 py-3 text-sm">{{ $subject->grade_level }}</td><td class="px-4 py-3 text-sm">{{ $subject->weekly_lessons }}</td><td class="px-4 py-3 text-sm">{{ $subject->is_active ? 'Active' : 'Inactive' }}</td><td class="px-4 py-3 text-right"><button wire:click="edit({{ $subject->id }})" class="mr-3 text-sm text-green-700">Edit</button><button wire:click="toggle({{ $subject->id }})" class="text-sm text-gray-600">{{ $subject->is_active ? 'Deactivate' : 'Activate' }}</button></td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-sm text-gray-400">No subjects configured.</td></tr>@endforelse</tbody></table></div>
    @if($showForm)<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div class="w-full max-w-xl rounded-xl bg-white p-6"><h3 class="mb-4 text-lg font-bold">{{ $editingId ? 'Edit subject' : 'Add subject' }}</h3><div class="grid grid-cols-1 gap-3 md:grid-cols-2"><input wire:model="form.name" placeholder="Subject name" class="rounded-lg border px-3 py-2 text-sm"><input wire:model="form.code" placeholder="Code e.g. MAT" class="rounded-lg border px-3 py-2 text-sm"><select wire:model="form.grade_level" class="rounded-lg border px-3 py-2 text-sm md:col-span-2"><option value="">Grade or level</option>@foreach($grades as $grade)<option value="{{ $grade }}">{{ $grade }}</option>@endforeach</select><input wire:model="form.weekly_lessons" type="number" min="1" max="50" placeholder="Lessons per week" class="rounded-lg border px-3 py-2 text-sm"></div><div class="mt-5 flex justify-end gap-2"><button wire:click="$set('showForm', false)" class="rounded-lg border px-4 py-2 text-sm">Cancel</button><button wire:click="save" class="rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white">Save subject</button></div></div></div>@endif
    @if($showAssignmentForm)<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div class="w-full max-w-xl rounded-xl bg-white p-6"><h3 class="mb-4 text-lg font-bold">Assign subject to class</h3><div class="grid gap-3"><select wire:model="assignmentForm.class_id" class="rounded-lg border px-3 py-2 text-sm"><option value="">Select class</option>@foreach($classes as $class)<option value="{{ $class->id }}">{{ $class->name }} ({{ $class->grade_level }})</option>@endforeach</select><select wire:model="assignmentForm.learning_area_id" class="rounded-lg border px-3 py-2 text-sm"><option value="">Select subject</option>@foreach($subjects->where('is_active', true) as $subject)<option value="{{ $subject->id }}">{{ $subject->name }} ({{ $subject->grade_level }})</option>@endforeach</select><input wire:model="assignmentForm.lessons_per_week" type="number" min="1" max="50" class="rounded-lg border px-3 py-2 text-sm" placeholder="Lessons per week"></div><div class="mt-5 flex justify-end gap-2"><button wire:click="$set('showAssignmentForm', false)" class="rounded-lg border px-4 py-2 text-sm">Cancel</button><button wire:click="assignToClass" class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Assign subject</button></div></div></div>@endif
</div>
