<div>
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h2 class="text-2xl font-bold text-gray-900">School timetable command centre</h2><p class="text-sm text-gray-500">Generate one complete, conflict-checked school timetable; verify it, then publish matching class and teacher copies together.</p></div><div class="flex flex-wrap gap-2"><input wire:model="academicYear" class="w-28 rounded-lg border px-3 py-2 text-sm" aria-label="Academic year"><select wire:model="term" class="rounded-lg border px-3 py-2 text-sm"><option value="1">Term 1</option><option value="2">Term 2</option><option value="3">Term 3</option></select><select wire:model.live="classId" class="rounded-lg border px-3 py-2 text-sm" aria-label="Class"><option value="">All classes</option>@foreach($classes as $class)<option value="{{ $class->id }}">{{ $class->grade_level }}{{ $class->name !== $class->grade_level ? ' - '.$class->name : '' }}</option>@endforeach</select><button wire:click="assignClassTeachers" wire:loading.attr="disabled" class="rounded-lg border border-green-700 px-4 py-2 text-sm font-semibold text-green-800">Assign class teachers</button><button wire:click="generate" wire:loading.attr="disabled" class="rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white">Generate full draft</button><button wire:click="verify" wire:loading.attr="disabled" class="rounded-lg bg-amber-600 px-4 py-2 text-sm font-semibold text-white">Verify selected draft</button><button wire:click="publish" wire:loading.attr="disabled" class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Publish verified version</button><a href="{{ route('admin.timetable.print', ['academicYear' => $academicYear, 'term' => $term, 'classId' => $classId ?: null]) }}" target="_blank" rel="noopener" class="rounded-lg border px-4 py-2 text-sm">Print timetable</a></div></div>
    <div class="mb-5 rounded-lg bg-blue-50 px-4 py-3 text-sm text-blue-800">CBC timetable blocks now follow the selected school template for each grade band. Practical subjects are still placed in morning double periods where possible.</div>
    <div class="mb-5 rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm text-gray-700"><strong>Readiness:</strong> {{ $readiness['classes'] }} active class(es), {{ $readiness['subjects'] }} class-subject assignment(s), and {{ $readiness['missing'] }} missing teacher allocation(s) for this term. With <strong>All classes</strong> selected, generation creates every class timetable from the shared block rules, then <strong>Publish all classes</strong> releases their matching teacher and learner views together.@if($readiness['missing']) <span class="text-amber-700">Assign real subject teachers in Academic Setup before generating. If a class teacher genuinely teaches every subject, set them on the class and use “Assign class teachers”.</span>@endif</div>
    @if($notice)<div class="mb-4 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">{{ $notice }}</div>@endif
    @error('academicYear')<div class="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{{ $message }}</div>@enderror
    <section class="mb-5 rounded-xl bg-white p-4 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3"><h3 class="font-bold text-gray-900">Versions</h3>@if($selectedVersionId)<div class="flex gap-3"><a href="{{ route('admin.timetable.pdf', $selectedVersionId) }}" target="_blank" class="text-sm font-semibold text-blue-700">PDF selected version</a><a href="{{ route('admin.timetable.classes.pdf', $selectedVersionId) }}" target="_blank" class="text-sm font-semibold text-blue-700">All class PDFs</a></div>@endif</div><div class="mt-3 flex flex-wrap gap-2">@forelse($versions as $version)<button wire:click="selectVersion({{ $version->id }})" class="rounded-lg border px-3 py-2 text-sm {{ $selectedVersionId === $version->id ? 'border-blue-600 bg-blue-50 text-blue-800' : 'border-gray-300' }}">v{{ $version->version_number }} · {{ ucfirst($version->state) }} · {{ $version->lesson_count }} lessons</button>@empty<span class="text-sm text-gray-500">No generated versions for this term.</span>@endforelse</div></section>
    @if($conflicts)<section class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4"><h3 class="font-bold text-red-900">Conflict report</h3><ul class="mt-2 list-disc space-y-1 pl-5 text-sm text-red-800">@foreach($conflicts as $conflict)<li>{{ $conflict['message'] ?? (($conflict['class'] ?? 'Timetable').' — '.($conflict['subject'] ?? 'configuration issue')) }}</li>@endforeach</ul></section>@endif
    @if($classId && $slots->isNotEmpty())
        <section class="mb-6 overflow-x-auto rounded-xl bg-white p-5 shadow-sm">
            <div class="mb-4"><h3 class="font-bold text-gray-900">{{ $slots->first()->schoolClass?->name }} weekly timetable</h3><p class="text-sm text-gray-500">Draft or published lessons shown in a printable day-and-period grid.</p></div>
            <table class="min-w-[760px] w-full border-collapse text-xs"><thead><tr class="bg-green-700 text-white"><th class="border border-green-800 p-2 text-left">Time</th>@foreach(['monday' => 'Monday', 'tuesday' => 'Tuesday', 'wednesday' => 'Wednesday', 'thursday' => 'Thursday', 'friday' => 'Friday'] as $day => $label)<th class="border border-green-800 p-2 text-left">{{ $label }}</th>@endforeach</tr></thead><tbody>@forelse($gridBlocks as $block)@if($block['is_break'])<tr class="bg-amber-50 text-amber-900"><th class="border p-2 text-left">{{ $block['start'] }}–{{ $block['end'] }}</th><td colspan="5" class="border p-2 text-center font-semibold">{{ $block['label'] }}</td></tr>@else<tr><th class="border bg-gray-50 p-2 text-left font-medium">{{ $block['start'] }}–{{ $block['end'] }}</th>@foreach(['monday','tuesday','wednesday','thursday','friday'] as $day)@php($slot = $gridSlots->get($day.'|'.$block['start']))<td class="border p-2 align-top {{ $slot ? 'bg-green-50' : 'text-gray-300' }}">@if($slot)<div class="font-semibold text-gray-900">{{ $slot->learningArea?->name }}</div><div class="mt-1 text-gray-600">{{ $slot->teacher?->full_name }}</div>@if($slot->venue)<div class="text-gray-500">{{ $slot->venue }}</div>@endif @else — @endif</td>@endforeach</tr>@endif @empty<tr><td colspan="6" class="p-8 text-center text-gray-500">Select a class to preview its timetable block.</td></tr>@endforelse</tbody></table>
        </section>
    @endif
    <div class="overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-3 py-3 text-left text-xs uppercase">Day</th><th class="px-3 py-3 text-left text-xs uppercase">Time</th><th class="px-3 py-3 text-left text-xs uppercase">Class</th><th class="px-3 py-3 text-left text-xs uppercase">Subject</th><th class="px-3 py-3 text-left text-xs uppercase">Teacher</th><th class="px-3 py-3 text-left text-xs uppercase">Room</th><th class="px-3 py-3 text-left text-xs uppercase">Status</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($slots as $slot)<tr><td class="px-3 py-2 text-sm capitalize">{{ $slot->day_of_week }}</td><td class="px-3 py-2 text-sm">{{ substr($slot->start_time, 0, 5) }} - {{ substr($slot->end_time, 0, 5) }}</td><td class="px-3 py-2 text-sm font-medium">{{ $slot->schoolClass?->name }}</td><td class="px-3 py-2 text-sm">{{ $slot->learningArea?->name }}</td><td class="px-3 py-2 text-sm">{{ $slot->teacher?->full_name }}</td><td class="px-3 py-2 text-sm">{{ $slot->venue ?: '-' }}</td><td class="px-3 py-2 text-sm">{{ $slot->is_active ? 'Published' : 'Draft' }}</td></tr>@empty<tr><td colspan="7" class="p-10 text-center text-sm text-gray-500">No timetable generated for this academic year and term.</td></tr>@endforelse</tbody></table></div>
</div>
