services:
  - type: web
    name: cbc-school-management
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: CBC School Management System
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        sync: false
      - key: ASSET_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_TIMEZONE
        value: Africa/Nairobi
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_CA
        sync: false
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        value: "true"
