<div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start">
        <div><h1 class="text-2xl font-bold text-gray-900">SMS Dashboard</h1><p class="mt-1 text-sm text-gray-600">Your school’s wallet, SMS purchases, messages and delivery activity.</p></div>
        <div class="flex gap-2"><a href="{{ route('admin.notifications.index') }}" class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Send SMS</a><a href="#buy-sms" class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Buy SMS</a></div>
    </div>
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <section class="rounded-xl border {{ $school->sms_credits > 0 ? 'border-blue-200' : 'border-red-300 bg-red-50' }} bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-blue-700">SMS balance</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ number_format($school->sms_credits) }}</p><p class="mt-1 text-sm text-gray-500">SMS remaining</p>@if(!$school->sms_credits)<a href="#buy-sms" class="mt-3 inline-block text-sm font-semibold text-red-700 underline">Buy SMS to send messages</a>@endif</section>
        <section class="rounded-xl border border-green-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-green-700">Total purchased</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ number_format($purchased) }}</p><p class="mt-1 text-sm text-gray-500">SMS credited after payment</p></section>
        <section class="rounded-xl border border-violet-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-violet-700">Total used</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ number_format($used) }}</p><p class="mt-1 text-sm text-gray-500">KSh {{ number_format($spent, 2) }} spent on SMS</p></section>
        <section class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-gray-600">School account</p><p class="mt-2 text-2xl font-bold {{ $school->is_active ? 'text-green-700' : 'text-red-700' }}">{{ $school->is_active ? 'Active' : 'Inactive' }}</p><p class="mt-2 text-sm text-gray-500">Last wallet activity: {{ $school->smsCreditTransactions()->first()?->created_at?->format('d M Y, H:i') ?? 'None' }}</p></section>
    </div>
    <section class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950">This page is only for SMS. It uses the platform M-Pesa till for SMS credits and never changes your school subscription or plan. Olympus credentials, provider inventory and other schools’ balances remain private to the platform Super Admin.</section>
    <section id="buy-sms" class="rounded-xl bg-white p-5 shadow-sm">
        <h2 class="font-bold text-gray-900">Buy SMS credits</h2><p class="mt-1 text-sm text-gray-500">Choose SMS units, approve the M-Pesa prompt, then this school wallet is credited after payment and provider-capacity checks.</p>
        <div class="mt-4 flex flex-wrap items-end gap-4"><label><span class="text-xs font-semibold uppercase text-gray-500">SMS units</span><input wire:model="smsUnits" type="number" min="10" class="mt-1 block w-40 rounded border px-3 py-2"></label><label><span class="text-xs font-semibold uppercase text-gray-500">M-Pesa phone</span><input wire:model="phone" placeholder="07XXXXXXXX" class="mt-1 block w-52 rounded border px-3 py-2"></label><div class="text-sm text-gray-700">Price: <strong>KSh {{ number_format($smsUnitPrice, 2) }}</strong> per SMS · Total: <strong>KSh {{ number_format($smsUnitPrice * $smsUnits, 2) }}</strong></div><button wire:click="buySmsCredits" wire:loading.attr="disabled" class="rounded-lg bg-indigo-700 px-4 py-2.5 text-sm font-semibold text-white">Pay for SMS credits</button></div>
        @error('phone')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror @error('smsUnits')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror
        @if($error)<div class="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{{ $error }}</div>@endif
        @if($pendingSmsStatus === 'pending')<div class="mt-4 rounded border border-yellow-200 bg-yellow-50 p-3 text-sm text-yellow-800">SMS order is awaiting M-Pesa confirmation. <button wire:click="checkSmsStatus" class="ml-2 font-semibold underline">Check status</button></div>@elseif($pendingSmsStatus === 'awaiting_allocation')<div class="mt-4 rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Payment is confirmed. The order is awaiting allocation because central provider capacity is insufficient.</div>@elseif($pendingSmsStatus === 'confirmed')<div class="mt-4 rounded border border-green-200 bg-green-50 p-3 text-sm text-green-800">SMS payment confirmed and credits added to this school wallet.</div>@elseif($pendingSmsStatus === 'failed')<div class="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">SMS payment did not complete.</div>@endif
    </section>
    <div class="grid gap-6 xl:grid-cols-2">
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-bold text-gray-900">Your SMS purchases</h2><div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead class="border-b text-left text-xs uppercase text-gray-500"><tr><th class="pb-2">Units</th><th class="pb-2">Amount</th><th class="pb-2">Status</th><th class="pb-2">Receipt</th></tr></thead><tbody class="divide-y">@forelse($recentOrders as $order)<tr><td class="py-3">{{ number_format($order->units) }}</td><td class="py-3">KSh {{ number_format((float)$order->amount, 2) }}</td><td class="py-3">{{ str_replace('_', ' ', ucfirst($order->status)) }}</td><td class="py-3">{{ $order->mpesa_receipt_number ?: '—' }}</td></tr>@empty<tr><td colspan="4" class="py-6 text-center text-gray-500">No SMS purchase orders yet.</td></tr>@endforelse</tbody></table></div></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-bold text-gray-900">Recent SMS messages</h2><div class="mt-4 space-y-3">@forelse($recentMessages as $message)<div class="border-b pb-3"><div class="flex justify-between gap-3"><strong class="text-sm text-gray-800">{{ $message->title ?: 'SMS message' }}</strong><span class="text-xs text-gray-500">{{ $message->created_at->format('d M, H:i') }}</span></div><p class="mt-1 truncate text-sm text-gray-600">{{ $message->message }}</p><p class="mt-1 text-xs text-gray-500">{{ $message->sent_count }}/{{ $message->total_recipients }} sent · {{ ucfirst($message->status) }}</p></div>@empty<p class="text-sm text-gray-500">No school SMS messages yet.</p>@endforelse</div></section>
    </div>
    <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-bold text-gray-900">Usage in the last 7 days</h2><div class="mt-4 grid gap-3 sm:grid-cols-4">@forelse($dailyUsage as $day)<div class="rounded-lg bg-gray-50 p-3"><p class="text-xs text-gray-500">{{ \Illuminate\Support\Carbon::parse($day->day)->format('D, d M') }}</p><p class="mt-1 text-lg font-bold">{{ number_format($day->units) }} SMS</p></div>@empty<p class="text-sm text-gray-500">No usage recorded in the last seven days.</p>@endforelse</div></section>
</div>
