<div class="space-y-6">
    <div><h2 class="text-2xl font-bold text-gray-900">Support tickets</h2><p class="text-sm text-gray-500">Submit a problem to the Super Admin and track its resolution.</p></div>
    @if(session('success'))<div class="rounded-lg bg-green-50 p-3 text-sm text-green-800">{{ session('success') }}</div>@endif
    @if(auth()->user()->can('submit support tickets'))
        <form wire:submit="submit" class="rounded-xl bg-white p-6 shadow-sm"><h3 class="font-bold">Submit a ticket</h3><div class="mt-4 grid gap-4 md:grid-cols-2"><input wire:model="subject" placeholder="Short description of the problem" class="rounded-lg border px-3 py-2 md:col-span-2"><select wire:model="priority" class="rounded-lg border px-3 py-2"><option value="low">Low priority</option><option value="normal">Normal priority</option><option value="high">High priority</option><option value="urgent">Urgent</option></select><textarea wire:model="description" rows="5" placeholder="Explain what happened, where it happened, and what you expected." class="rounded-lg border px-3 py-2 md:col-span-2"></textarea></div>@error('subject')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror @error('description')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror<button class="mt-4 rounded-lg bg-green-700 px-4 py-2 font-semibold text-white">Submit ticket</button></form>
    @endif
    <div class="overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full divide-y"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left text-xs uppercase">Ticket</th><th class="px-4 py-3 text-left text-xs uppercase">Subject</th><th class="px-4 py-3 text-left text-xs uppercase">Submitted by</th><th class="px-4 py-3 text-left text-xs uppercase">Priority</th><th class="px-4 py-3 text-left text-xs uppercase">Status and feedback</th>@if($isSuperAdmin)<th class="px-4 py-3"></th>@endif</tr></thead><tbody class="divide-y">@forelse($tickets as $ticket)<tr><td class="px-4 py-3 text-sm font-semibold">{{ $ticket->ticket_number }}</td><td class="px-4 py-3 text-sm"><p class="font-semibold">{{ $ticket->subject }}</p><p class="max-w-md whitespace-pre-wrap text-xs text-gray-500">{{ $ticket->description }}</p></td><td class="px-4 py-3 text-sm"><p>{{ $ticket->creator?->name }}</p><p class="text-xs text-gray-500">{{ $ticket->creator?->email }}</p></td><td class="px-4 py-3 text-sm capitalize">{{ $ticket->priority }}</td><td class="px-4 py-3 text-sm"><span class="capitalize">{{ $ticket->status }}</span>@if($ticket->resolution)<p class="mt-2 whitespace-pre-wrap text-xs text-green-700"><strong>Feedback:</strong> {{ $ticket->resolution }}</p>@elseif(! $isSuperAdmin)<p class="mt-2 text-xs text-gray-500">Awaiting Super Admin feedback.</p>@endif</td>@if($isSuperAdmin)<td class="px-4 py-3 text-right"><button wire:click="edit({{ $ticket->id }})" class="text-sm font-semibold text-green-700">Diagnose / update</button></td>@endif</tr>@empty<tr><td colspan="6" class="p-8 text-center text-sm text-gray-500">No support tickets found.</td></tr>@endforelse</tbody></table><div class="border-t bg-gray-50 px-4 py-3">{{ $tickets->links() }}</div></div>
    @if($isSuperAdmin && $editingId)<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form wire:submit="updateTicket" class="w-full max-w-xl rounded-xl bg-white p-6 shadow-xl"><div class="flex items-center justify-between"><h3 class="text-lg font-bold">Super Admin diagnosis</h3><button type="button" wire:click="$set('editingId', null)">&times;</button></div><select wire:model="status" class="mt-4 w-full rounded-lg border px-3 py-2"><option value="open">Open</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><textarea wire:model="diagnosticNotes" rows="5" placeholder="Diagnosis, logs checked, and findings" class="mt-4 w-full rounded-lg border px-3 py-2"></textarea><textarea wire:model="resolution" rows="4" placeholder="Resolution or instructions for the reporter" class="mt-4 w-full rounded-lg border px-3 py-2"></textarea><button class="mt-4 rounded-lg bg-green-700 px-4 py-2 font-semibold text-white">Save diagnosis</button></form></div>@endif
</div>
