@extends('layouts.admin')
@section('header', 'Learner report')
@section('content')
<div class="space-y-6">
    <div class="flex flex-wrap items-center justify-between gap-3">
        <div><h2 class="text-2xl font-bold text-gray-900">{{ $learner->full_name }}</h2><p class="text-sm text-gray-500">{{ $learner->admission_number }} · {{ $learner->schoolClass?->name ?: 'No class assigned' }}</p></div>
        <a href="{{ route('admin.reports.index') }}" class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Back to analytics</a>
    </div>
    <section class="card overflow-hidden"><div class="border-b p-5"><h3 class="font-bold text-gray-900">{{ $exam ? $exam->name : 'Latest result' }}</h3><p class="text-xs text-gray-500">Saved marks and grades for this learner.</p></div><div class="overflow-x-auto"><table class="min-w-full"><thead class="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">Subject</th><th class="px-4 py-3">Exam</th><th class="px-4 py-3">Marks</th><th class="px-4 py-3">Percentage</th><th class="px-4 py-3">Grade</th><th class="px-4 py-3">Remarks</th></tr></thead><tbody class="divide-y">@forelse($results as $result)<tr><td class="px-4 py-3 text-sm font-semibold">{{ $result->exam->learningArea?->name ?: 'Unknown subject' }}</td><td class="px-4 py-3 text-sm">{{ $result->exam->name }}</td><td class="px-4 py-3 text-sm">{{ $result->marks_obtained }} / {{ $result->total_marks }}</td><td class="px-4 py-3 text-sm">{{ number_format($result->percentage, 2) }}%</td><td class="px-4 py-3 text-sm font-bold">{{ $result->grade ?: 'Not graded' }}</td><td class="px-4 py-3 text-sm">{{ $result->remarks ?: '-' }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-sm text-gray-400">No results have been entered for this learner.</td></tr>@endforelse</tbody></table></div></section>
    <section class="card p-5"><h3 class="font-bold text-gray-900">Performance trend</h3><p class="text-xs text-gray-500">Mean percentage across all published results in {{ config('school.academic_year') }}.</p><div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@forelse($trend as $item)<div class="rounded-xl bg-gray-50 p-4"><p class="truncate text-sm font-semibold text-gray-900">{{ $item['exam'] }}</p><p class="mt-2 text-2xl font-bold text-green-700">{{ number_format($item['percentage'], 1) }}%</p><p class="text-xs text-gray-500">{{ $item['subject'] ?: 'Subject not set' }} · Grade {{ $item['grade'] }}</p></div>@empty<p class="text-sm text-gray-400">No trend data available.</p>@endforelse</div></section>
</div>
@endsection
