<?php
use Illuminate\Support\Facades\Route;
use App\Livewire\Students\StudentList;
use App\Livewire\Assessment\BulkAssessmentEntry;
use App\Livewire\Notifications\SendNotification;
use App\Livewire\Notifications\SchoolSmsDashboard;
use App\Livewire\Exams\ExamManager;
use App\Livewire\Inventory\InventoryList;
use App\Livewire\Notes\LearningNotesList;
use App\Livewire\Admin\AcademicSetup;
use App\Livewire\Admin\StaffManager;
use App\Livewire\Admin\SubjectManager;
use App\Livewire\Admin\ReportCardTemplates;
use App\Livewire\Admin\GradeManager;
use App\Livewire\Admin\AcademicPeriods;
use App\Livewire\Admin\RoleManager;
use App\Livewire\Admin\PromotionManager;
use App\Livewire\Admin\TimetableManager;
use App\Livewire\Admin\ExamTimetableManager;
use App\Livewire\Admin\ParentManager;
use App\Models\FeeInvoice;
use App\Http\Controllers\AdminSettingsController;
use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\ExamReportsController;
use App\Http\Controllers\ReportCardController;
use App\Http\Controllers\MarksImportTemplateController;
use App\Http\Controllers\DriveStoreController;
use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\ImpersonationController;
use App\Livewire\Support\SupportTicketCenter;
use App\Livewire\Support\DiagnosticCenter;
use App\Livewire\Admin\LegalPolicyManager;
use App\Livewire\Admin\BackupCenter;
use App\Livewire\Admin\SystemLogViewer;
use App\Livewire\Admin\UserAccountManager;
use App\Livewire\SuperAdmin\SchoolManager;
use App\Livewire\SuperAdmin\PackageManager;
use App\Livewire\SuperAdmin\PlatformFinance;
use App\Livewire\SuperAdmin\PlatformAnalytics;
use App\Livewire\SuperAdmin\BroadcastCenter;
use App\Livewire\SuperAdmin\SuperAdminDashboard;
use App\Livewire\SuperAdmin\PlatformMaintenance;
use App\Livewire\SuperAdmin\PlatformSettings;
use App\Livewire\SuperAdmin\SmsControlCenter;
use App\Livewire\SuperAdmin\InvoiceManager;
use App\Livewire\Admin\IdCardGenerator;
use App\Http\Controllers\TimetableController;
use App\Http\Controllers\RiskPredictionController;
use App\Http\Controllers\PastExamDocumentController;
use App\Http\Controllers\NewsletterController;

// The enclosing admin route group already restricts this landing page to
// leadership roles. Do not make login/consent completion depend on an
// optional feature permission that may be repaired later in the request
// lifecycle; individual administrative features stay permission-protected.
Route::get('/dashboard', AdminDashboardController::class)->name('dashboard');
Route::get('/platform-dashboard', SuperAdminDashboard::class)->middleware('role:super-admin')->name('platform-dashboard.index');
Route::get('/platform-maintenance', PlatformMaintenance::class)->middleware('role:super-admin')->name('platform-maintenance.index');
Route::get('/platform-settings', PlatformSettings::class)->middleware('role:super-admin')->name('platform-settings.index');
Route::get('/sms-control', SmsControlCenter::class)->middleware('role:super-admin')->name('sms-control.index');
// School administrators can submit and track their own tickets. Only the
// super-admin receives the management permission and can see every ticket.
Route::get('/support', SupportTicketCenter::class)->middleware('permission:submit support tickets')->name('support.index');
Route::get('/diagnostics', DiagnosticCenter::class)->middleware('role:super-admin')->name('diagnostics.index');
Route::get('/legal-policies', LegalPolicyManager::class)->middleware('role:super-admin')->name('legal-policies.index');
Route::get('/schools', SchoolManager::class)->middleware('role:super-admin')->name('schools.index');
Route::get('/plans', PackageManager::class)->middleware('role:super-admin')->name('plans.index');
Route::get('/invoices', InvoiceManager::class)->middleware('role:super-admin')->name('invoices.index');
Route::get('/platform-finance', PlatformFinance::class)->middleware('role:super-admin')->name('platform-finance.index');
Route::get('/platform-analytics', PlatformAnalytics::class)->middleware('role:super-admin')->name('platform-analytics.index');
Route::get('/ai-risk-predictions', [RiskPredictionController::class, 'platform'])->middleware('role:super-admin')->name('risk.platform');
Route::post('/ai-risk-predictions/retrain', [RiskPredictionController::class, 'train'])->middleware('role:super-admin')->name('risk.train');
Route::post('/ai-risk-predictions/recompute', [RiskPredictionController::class, 'recompute'])->middleware('role:super-admin')->name('risk.recompute');
Route::get('/broadcasts', BroadcastCenter::class)->middleware('role:super-admin')->name('broadcasts.index');
Route::get('/backups', BackupCenter::class)->middleware('permission:manage system settings')->name('backups.index');
Route::get('/user-accounts', UserAccountManager::class)->middleware('permission:manage users')->name('user-accounts.index');
Route::get('/system-logs', SystemLogViewer::class)->middleware('role:super-admin')->name('system-logs.index');
Route::get('/impersonate', [ImpersonationController::class, 'index'])->middleware('role:super-admin|school-admin|headteacher|principal|deputy-headteacher|deputy')->name('impersonate.index');
Route::post('/impersonate/{user}', [ImpersonationController::class, 'start'])->middleware('role:super-admin|school-admin|headteacher|principal|deputy-headteacher|deputy')->name('impersonate.start');
Route::get('/students', StudentList::class)->middleware('permission:view students')->name('students.index');
Route::get('/students/import', StudentList::class)->middleware('permission:create students')->name('students.import');
Route::get('/students/{learner}/report-card', [ReportCardController::class, 'download'])->middleware('permission:view report cards')->name('students.report-card');
Route::get('/assessment', BulkAssessmentEntry::class)->middleware('permission:view assessments')->name('assessment.index');
Route::get('/notifications', SendNotification::class)->middleware(['permission:view notifications', 'feature:notifications'])->name('notifications.index');
Route::get('/sms', SchoolSmsDashboard::class)->middleware(['permission:view notifications', 'feature:notifications'])->name('sms.index');
Route::get('/exams', ExamManager::class)->middleware('permission:view exams')->name('exams.index');
Route::get('/exams/archive', [PastExamDocumentController::class, 'index'])->middleware('permission:view exams')->name('exams.archive');
Route::post('/exams/archive', [PastExamDocumentController::class, 'store'])->middleware('permission:manage exams')->name('exams.archive.store');
Route::get('/exams/archive/{document}', [PastExamDocumentController::class, 'show'])->middleware('permission:view exams')->name('exams.archive.show');
Route::delete('/exams/archive/{document}', [PastExamDocumentController::class, 'destroy'])->middleware('permission:manage exams')->name('exams.archive.destroy');
Route::get('/exams/{exam}/marks-template', [MarksImportTemplateController::class, 'download'])->middleware('permission:enter marks')->name('exams.marks-template');
Route::get('/exams/{exam}/report-cards', [ExamReportsController::class, 'resultCards'])->middleware('permission:view report cards')->name('exams.report-cards');
Route::get('/exams/report-cards/export/{export}', [ExamReportsController::class, 'downloadExport'])->middleware('permission:view report cards')->name('exams.report-cards.export');
Route::get('/exams/{exam}/merit-list', [ExamReportsController::class, 'meritList'])->middleware('permission:view report cards')->name('exams.merit-list');
Route::get('/inventory', InventoryList::class)->middleware(['permission:view inventory', 'feature:inventory'])->name('inventory.index');
Route::get('/id-cards', IdCardGenerator::class)->middleware(['permission:view students', 'feature:id_cards'])->name('id-cards.index');
Route::get('/notes', LearningNotesList::class)->middleware(['permission:view notes', 'feature:lesson_plans'])->name('notes.index');
Route::get('/fees/receipt/{invoice}', function (FeeInvoice $invoice) {
    $payment = $invoice->payments()->latest('paid_at')->first();

    abort_unless($payment, 404, 'Receipt not found.');

    return view('pdf.fee-receipt', compact('payment'));
})->middleware('permission:view fees')->name('fees.receipt');
Route::get('/staff', StaffManager::class)->middleware('permission:view staff')->name('staff.index');
Route::get('/staff/import', StaffManager::class)->middleware('permission:manage staff')->name('staff.import');
Route::get('/parents', ParentManager::class)->middleware('permission:view students')->name('parents.index');
Route::get('/timetable', TimetableManager::class)->middleware(['permission:view timetable', 'feature:timetable'])->name('timetable.index');
Route::get('/exam-timetable', ExamTimetableManager::class)->middleware(['permission:view timetable', 'feature:timetable'])->name('exam-timetable.index');
Route::get('/timetable/print', [TimetableController::class, 'printSchool'])->middleware('permission:view timetable')->name('timetable.print');
Route::get('/timetable/{version}/pdf', [TimetableController::class, 'pdf'])->middleware('permission:view timetable')->name('timetable.pdf');
Route::get('/timetable/{version}/teacher/{teacher}/pdf', [TimetableController::class, 'teacherPdf'])->middleware('permission:view timetable')->name('timetable.teacher.pdf');
Route::get('/timetable/{version}/classes/pdf', [TimetableController::class, 'allClassesPdf'])->middleware('permission:manage timetable')->name('timetable.classes.pdf');
Route::post('/timetable/publish', [TimetableController::class, 'publish'])->middleware('permission:manage timetable')->name('timetable.publish');
Route::post('/timetable/unpublish', [TimetableController::class, 'unpublish'])->middleware('permission:manage timetable')->name('timetable.unpublish');
Route::get('/reports', [AnalyticsController::class, 'index'])->middleware('permission:view analytics')->name('reports.index');
Route::get('/at-risk-learners', [RiskPredictionController::class, 'index'])->middleware(['permission:view analytics', 'feature:predictive_analytics'])->name('risk.index');
Route::get('/at-risk-learners/{prediction}', [RiskPredictionController::class, 'show'])->middleware(['permission:view analytics', 'feature:predictive_analytics'])->name('risk.show');
Route::get('/reports/student/{learner}', [AnalyticsController::class, 'student'])->middleware('permission:view analytics')->name('reports.student');
Route::get('/reports/export', [AnalyticsController::class, 'export'])->middleware('permission:export reports')->name('reports.export');
Route::middleware(['feature:newsletters', 'permission:manage newsletters', 'role:school-admin|headteacher|principal|deputy-headteacher|deputy'])->group(function () {
    Route::get('/newsletters', [NewsletterController::class, 'index'])->name('newsletters.index');
    Route::get('/newsletters/create', [NewsletterController::class, 'create'])->name('newsletters.create');
    Route::post('/newsletters', [NewsletterController::class, 'store'])->name('newsletters.store');
    Route::get('/newsletters/{newsletter}/edit', [NewsletterController::class, 'edit'])->name('newsletters.edit');
    Route::put('/newsletters/{newsletter}', [NewsletterController::class, 'update'])->name('newsletters.update');
    Route::post('/newsletters/{newsletter}/publish', [NewsletterController::class, 'publish'])->name('newsletters.publish');
    Route::post('/newsletters/{newsletter}/unpublish', [NewsletterController::class, 'unpublish'])->name('newsletters.unpublish');
    Route::delete('/newsletters/{newsletter}', [NewsletterController::class, 'destroy'])->name('newsletters.destroy');
    Route::get('/newsletters/{newsletter}/print', [NewsletterController::class, 'print'])->name('newsletters.print');
});
Route::get('/drive-store', [DriveStoreController::class, 'index'])->middleware('permission:view report cards')->name('drive-store.index');
Route::post('/drive-store/sync', [DriveStoreController::class, 'syncRecords'])->middleware('permission:manage system settings')->name('drive-store.sync');
Route::post('/drive-store/import-records', [DriveStoreController::class, 'importRecords'])->middleware('permission:create students')->name('drive-store.import-records');
Route::post('/drive-store/repair-class-subjects', [DriveStoreController::class, 'repairClassSubjects'])->middleware('permission:manage curriculum')->name('drive-store.repair-class-subjects');
Route::get('/settings', fn() => view('admin.settings.index'))->middleware('permission:manage system settings')->name('settings.index');
Route::get('/report-forms', ReportCardTemplates::class)->middleware('permission:view report cards')->name('report-forms.index');
Route::get('/grades', GradeManager::class)->middleware('permission:manage curriculum')->name('grades.index');
Route::get('/academic-periods', AcademicPeriods::class)->middleware('permission:manage curriculum')->name('academic-periods.index');
Route::get('/promotions', PromotionManager::class)->middleware('permission:manage promotions')->name('promotions.index');
Route::get('/roles', RoleManager::class)->middleware('permission:manage roles')->name('roles.index');
Route::get('/classes', AcademicSetup::class)->middleware('permission:manage curriculum')->name('classes.index');
Route::get('/subjects', SubjectManager::class)->middleware('permission:manage curriculum')->name('subjects.index');
Route::put('/settings', [AdminSettingsController::class, 'update'])->middleware('permission:manage system settings')->name('settings.update');
Route::post('/settings/sms-test', [AdminSettingsController::class, 'testSms'])->middleware('permission:manage system settings')->name('settings.sms-test');
Route::post('/settings/drive-test', [AdminSettingsController::class, 'testDrive'])->middleware('permission:manage system settings')->name('settings.drive-test');
Route::get('/settings/google-drive/connect', [AdminSettingsController::class, 'connectDrive'])->middleware('permission:manage system settings')->name('settings.google-drive.connect');
Route::get('/settings/google-drive/callback', [AdminSettingsController::class, 'googleDriveCallback'])->middleware('permission:manage system settings')->name('settings.google-drive.callback');
Route::post('/settings/google-drive/disconnect', [AdminSettingsController::class, 'disconnectDrive'])->middleware('permission:manage system settings')->name('settings.google-drive.disconnect');
Route::get('/kemis', fn() => view('admin.kemis.index'))->middleware(['permission:sync kemis', 'feature:kemis'])->name('kemis.index');
