<?php
use Illuminate\Support\Facades\Route;
use App\Livewire\Students\StudentList;
use App\Livewire\Assessment\BulkAssessmentEntry;
use App\Livewire\Notifications\SendNotification;
use App\Livewire\Notifications\SmsBalance;
use App\Livewire\Exams\ExamManager;
use App\Livewire\Inventory\InventoryList;
use App\Livewire\Notes\LearningNotesList;
use App\Livewire\Admin\AcademicSetup;
use App\Livewire\Admin\StaffManager;
use App\Livewire\Admin\SubjectManager;
use App\Livewire\Admin\ReportCardTemplates;
use App\Livewire\Admin\GradeManager;
use App\Livewire\Admin\AcademicPeriods;
use App\Livewire\Admin\RoleManager;
use App\Livewire\Admin\PromotionManager;
use App\Livewire\Admin\TimetableManager;
use App\Livewire\Admin\ExamTimetableManager;
use App\Livewire\Admin\ParentManager;
use App\Models\FeeInvoice;
use App\Http\Controllers\AdminSettingsController;
use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\ExamReportsController;
use App\Http\Controllers\ReportCardController;
use App\Http\Controllers\MarksImportTemplateController;

Route::get('/dashboard', fn() => view('admin.dashboard'))->middleware('permission:view students')->name('dashboard');
Route::get('/students', StudentList::class)->middleware('permission:view students')->name('students.index');
Route::get('/students/import', StudentList::class)->middleware('permission:create students')->name('students.import');
Route::get('/students/{learner}/report-card', [ReportCardController::class, 'download'])->middleware('permission:view report cards')->name('students.report-card');
Route::get('/assessment', BulkAssessmentEntry::class)->middleware('permission:view assessments')->name('assessment.index');
Route::get('/notifications', SendNotification::class)->middleware('permission:view notifications')->name('notifications.index');
Route::get('/sms', SmsBalance::class)->middleware('permission:view notifications')->name('sms.index');
Route::get('/exams', ExamManager::class)->middleware('permission:view exams')->name('exams.index');
Route::get('/exams/{exam}/marks-template', [MarksImportTemplateController::class, 'download'])->middleware('permission:enter marks')->name('exams.marks-template');
Route::get('/exams/{exam}/report-cards', [ExamReportsController::class, 'resultCards'])->middleware('permission:view report cards')->name('exams.report-cards');
Route::get('/exams/report-cards/export/{export}', [ExamReportsController::class, 'downloadExport'])->middleware('permission:view report cards')->name('exams.report-cards.export');
Route::get('/exams/{exam}/merit-list', [ExamReportsController::class, 'meritList'])->middleware('permission:view report cards')->name('exams.merit-list');
Route::get('/inventory', InventoryList::class)->middleware('permission:view inventory')->name('inventory.index');
Route::get('/notes', LearningNotesList::class)->middleware('permission:view notes')->name('notes.index');
Route::get('/fees/receipt/{invoice}', function (FeeInvoice $invoice) {
    $payment = $invoice->payments()->latest('paid_at')->first();

    abort_unless($payment, 404, 'Receipt not found.');

    return view('pdf.fee-receipt', compact('payment'));
})->middleware('permission:view fees')->name('fees.receipt');
Route::get('/staff', StaffManager::class)->middleware('permission:view staff')->name('staff.index');
Route::get('/staff/import', StaffManager::class)->middleware('permission:manage staff')->name('staff.import');
Route::get('/parents', ParentManager::class)->middleware('permission:view students')->name('parents.index');
Route::get('/timetable', TimetableManager::class)->middleware('permission:view timetable')->name('timetable.index');
Route::get('/exam-timetable', ExamTimetableManager::class)->middleware('permission:view timetable')->name('exam-timetable.index');
Route::get('/reports', [AnalyticsController::class, 'index'])->middleware('permission:view analytics')->name('reports.index');
Route::get('/reports/student/{learner}', [AnalyticsController::class, 'student'])->middleware('permission:view analytics')->name('reports.student');
Route::get('/reports/export', [AnalyticsController::class, 'export'])->middleware('permission:export reports')->name('reports.export');
Route::get('/settings', fn() => view('admin.settings.index'))->middleware('permission:manage system settings')->name('settings.index');
Route::get('/report-forms', ReportCardTemplates::class)->middleware('permission:view report cards')->name('report-forms.index');
Route::get('/grades', GradeManager::class)->middleware('permission:manage curriculum')->name('grades.index');
Route::get('/academic-periods', AcademicPeriods::class)->middleware('permission:manage curriculum')->name('academic-periods.index');
Route::get('/promotions', PromotionManager::class)->middleware('permission:manage promotions')->name('promotions.index');
Route::get('/roles', RoleManager::class)->middleware('permission:manage roles')->name('roles.index');
Route::get('/classes', AcademicSetup::class)->middleware('permission:manage curriculum')->name('classes.index');
Route::get('/subjects', SubjectManager::class)->middleware('permission:manage curriculum')->name('subjects.index');
Route::put('/settings', [AdminSettingsController::class, 'update'])->middleware('permission:manage system settings')->name('settings.update');
Route::post('/settings/sms-test', [AdminSettingsController::class, 'testSms'])->middleware('permission:manage system settings')->name('settings.sms-test');
Route::get('/kemis', fn() => view('admin.kemis.index'))->middleware('permission:sync kemis')->name('kemis.index');
