@extends('layouts.admin')
@section('header', 'Settings')
@section('content')
<div class="space-y-6">
    @if(session('success'))<div class="rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ route('admin.settings.update') }}" enctype="multipart/form-data" class="space-y-6">
        @csrf @method('PUT')
        <section class="card p-6"><h2 class="text-xl font-bold text-gray-800">School settings</h2><p class="mb-5 text-sm text-gray-500">These values are saved in the database and used by reports, receipts, and portals.</p><div class="grid grid-cols-1 gap-4 md:grid-cols-2">
            @foreach([['name','School name',config('school.name'),true],['motto','Motto',config('school.motto'),false],['academic_year','Academic year',config('school.academic_year'),true],['current_term','Current term (1-3)',config('school.current_term'),true],['address','Address',config('school.address'),false],['phone','Phone',config('school.phone'),false],['email','Email',config('school.email'),false]] as [$key,$label,$value,$required])<label class="block"><span class="text-xs font-semibold uppercase tracking-wide text-gray-500">{{ $label }}</span><input name="{{ $key }}" value="{{ old($key, $value) }}" {{ $required ? 'required' : '' }} class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label>@endforeach
            <label class="block"><span class="text-xs font-semibold uppercase tracking-wide text-gray-500">School type</span><select name="type" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm">@foreach(['primary','secondary','mixed'] as $type)<option value="{{ $type }}" @selected(old('type', config('school.type')) === $type)>{{ ucfirst($type) }}</option>@endforeach</select></label>
            <label class="block md:col-span-2"><span class="text-xs font-semibold uppercase tracking-wide text-gray-500">Official school logo</span><input name="logo" type="file" accept="image/jpeg,image/png" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"> <span class="text-xs text-gray-500">Upload JPG or PNG, maximum 2 MB. This logo appears on report cards and official receipts.</span>@if(config('school.logo_data'))<img src="{{ config('school.logo_data') }}" alt="Current school logo" class="mt-3 h-20 w-20 rounded-lg border border-gray-200 object-contain p-1">@endif @error('logo')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label>
            <label class="flex items-center gap-3 rounded-lg border border-yellow-200 bg-yellow-50 p-4 md:col-span-2"><input type="hidden" name="maintenance_mode" value="0"><input name="maintenance_mode" type="checkbox" value="1" @checked(old('maintenance_mode', config('school.maintenance_mode'))) class="h-5 w-5 rounded border-gray-300 text-green-700"><span><span class="block text-sm font-semibold text-gray-800">Maintenance mode</span><span class="block text-xs text-gray-600">Visitors and non-admin users will see the maintenance animation. Admins can still log in and turn this off.</span></span></label>
            <label class="block md:col-span-2"><span class="text-xs font-semibold uppercase tracking-wide text-gray-500">Maintenance message</span><textarea name="maintenance_message" rows="2" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm">{{ old('maintenance_message', config('school.maintenance_message')) }}</textarea></label>
        </div></section>
        <section class="card p-6"><h2 class="text-lg font-bold text-gray-800">M-Pesa Daraja API</h2><p class="mb-5 text-sm text-gray-500">Leave secret fields blank to keep the currently saved credential. Never paste credentials into source control.</p><div class="grid grid-cols-1 gap-4 md:grid-cols-2">
            <label>Environment<select name="mpesa_env" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"><option value="sandbox" @selected(old('mpesa_env', config('services.mpesa.env')) === 'sandbox')>Sandbox</option><option value="production" @selected(old('mpesa_env', config('services.mpesa.env')) === 'production')>Production</option></select></label>
            @foreach([['mpesa_consumer_key','Consumer key'],['mpesa_consumer_secret','Consumer secret'],['mpesa_shortcode','Business shortcode'],['mpesa_passkey','Lipa na M-Pesa passkey'],['mpesa_callback_url','Callback URL'],['mpesa_confirmation_url','Confirmation URL'],['mpesa_validation_url','Validation URL']] as [$key,$label])<label>{{ $label }}<input name="{{ $key }}" value="{{ in_array($key, ['mpesa_consumer_key','mpesa_consumer_secret','mpesa_passkey']) ? '' : old($key, config('services.mpesa.'.substr($key, 6))) }}" placeholder="{{ in_array($key, ['mpesa_consumer_key','mpesa_consumer_secret','mpesa_passkey']) && config('services.mpesa.'.substr($key, 6)) ? 'Saved - leave blank to keep' : '' }}" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"></label>@endforeach
        </div></section>
        <section class="card p-6"><h2 class="text-lg font-bold text-gray-800">Africa's Talking SMS API</h2><div class="grid grid-cols-1 gap-4 md:grid-cols-2">
            <label>Environment<select name="at_env" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"><option value="sandbox" @selected(old('at_env', config('services.africastalking.env')) === 'sandbox')>Sandbox</option><option value="production" @selected(old('at_env', config('services.africastalking.env')) === 'production')>Production</option></select></label>
            @foreach([['at_api_key','API key'],['at_username','Username'],['at_sender_id','Sender ID']] as [$key,$label])<label>{{ $label }}<input name="{{ $key }}" value="{{ in_array($key, ['at_api_key']) ? '' : old($key, config('services.africastalking.'.substr($key, 3))) }}" placeholder="{{ $key === 'at_api_key' && config('services.africastalking.api_key') ? 'Saved - leave blank to keep' : '' }}" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"></label>@endforeach
        </div></section>
        <section class="card p-6"><h2 class="text-lg font-bold text-gray-800">Firebase push notifications</h2><div class="grid grid-cols-1 gap-4 md:grid-cols-2">@foreach([['firebase_server_key','Server key'],['firebase_project_id','Project ID']] as [$key,$label])<label>{{ $label }}<input name="{{ $key }}" value="{{ $key === 'firebase_server_key' ? '' : old($key, config('services.firebase.'.substr($key, 9))) }}" placeholder="{{ $key === 'firebase_server_key' && config('services.firebase.server_key') ? 'Saved - leave blank to keep' : '' }}" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"></label>@endforeach</div></section>
        <section class="card p-6"><h2 class="text-lg font-bold text-gray-800">KEMIS API</h2><div class="grid grid-cols-1 gap-4 md:grid-cols-2">@foreach([['kemis_api_url','API URL'],['kemis_api_key','API key'],['kemis_school_code','School code']] as [$key,$label])<label>{{ $label }}<input name="{{ $key }}" value="{{ $key === 'kemis_api_key' ? '' : old($key, config('services.kemis.'.substr($key, 6))) }}" placeholder="{{ $key === 'kemis_api_key' && config('services.kemis.api_key') ? 'Saved - leave blank to keep' : '' }}" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"></label>@endforeach</div></section>
        <button class="rounded-lg bg-green-700 px-6 py-3 text-sm font-semibold text-white hover:bg-green-800">Save all settings and API configuration</button>
    </form>
</div>
@endsection
