@extends('layouts.admin')
@section('header', 'Settings')
@section('content')
<div class="space-y-6">
    @if(session('success'))<div class="rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ route('admin.settings.update') }}" enctype="multipart/form-data" class="space-y-6">
        @csrf @method('PUT')
        <section class="card p-6"><h2 class="text-xl font-bold text-gray-800">School settings</h2><p class="mb-5 text-sm text-gray-500">These values are saved in the database and used by reports, receipts, and portals.</p><div class="grid grid-cols-1 gap-4 md:grid-cols-2">
            @foreach([['name','School name',config('school.name'),true],['motto','Motto',config('school.motto'),false],['academic_year','Academic year',config('school.academic_year'),true],['current_term','Current term (1-3)',config('school.current_term'),true],['address','Address',config('school.address'),false],['phone','Phone',config('school.phone'),false],['email','Email',config('school.email'),false]] as [$key,$label,$value,$required])<label class="block"><span class="text-xs font-semibold uppercase tracking-wide text-gray-500">{{ $label }}</span><input name="{{ $key }}" value="{{ old($key, $value) }}" {{ $required ? 'required' : '' }} class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label>@endforeach
            <label class="block"><span class="text-xs font-semibold uppercase tracking-wide text-gray-500">School type</span><select name="type" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm">@foreach(['primary','secondary','mixed'] as $type)<option value="{{ $type }}" @selected(old('type', config('school.type')) === $type)>{{ ucfirst($type) }}</option>@endforeach</select></label>
            <label class="block md:col-span-2"><span class="text-xs font-semibold uppercase tracking-wide text-gray-500">Official school logo</span><input name="logo" type="file" accept="image/jpeg,image/png" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"><span class="text-xs text-gray-500">JPG or PNG, maximum 2 MB.</span>@if(config('school.logo_data'))<img src="{{ config('school.logo_data') }}" alt="Current school logo" class="mt-3 h-20 w-20 rounded-lg border object-contain p-1">@endif</label>
            <label class="flex items-center gap-3 rounded-lg border border-yellow-200 bg-yellow-50 p-4 md:col-span-2"><input type="hidden" name="maintenance_mode" value="0"><input name="maintenance_mode" type="checkbox" value="1" @checked(old('maintenance_mode', config('school.maintenance_mode'))) class="h-5 w-5"><span><span class="block text-sm font-semibold">Maintenance mode</span><span class="block text-xs">Visitors and non-admin users see the maintenance page.</span></span></label>
            <label class="block md:col-span-2"><span class="text-xs font-semibold uppercase tracking-wide text-gray-500">Maintenance message</span><textarea name="maintenance_message" rows="2" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm">{{ old('maintenance_message', config('school.maintenance_message')) }}</textarea></label>
        </div></section>
        <section class="card border-2 border-green-100 p-6"><h2 class="text-lg font-bold text-gray-800">Olympus SMS API</h2><p class="mb-5 text-sm text-gray-500">Messages are sent through Olympus SMS. Leave the token blank to keep the saved encrypted token.</p><div class="grid grid-cols-1 gap-4 md:grid-cols-2">
            <label class="md:col-span-2">API URL<input name="olympus_sms_api_url" value="{{ old('olympus_sms_api_url', config('services.olympus_sms.api_url')) }}" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"></label>
            <label>API token<input name="olympus_sms_api_token" value="" placeholder="{{ config('services.olympus_sms.api_token') ? 'Saved - leave blank to keep' : 'Paste Olympus API token' }}" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"></label>
            <label>Sender ID<input name="olympus_sms_sender_id" value="{{ old('olympus_sms_sender_id', config('services.olympus_sms.sender_id', 'SCHOOL')) }}" maxlength="11" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"></label>
        </div></section>
        <section class="card p-6"><h2 class="text-lg font-bold text-gray-800">M-Pesa Daraja API</h2><div class="grid grid-cols-1 gap-4 md:grid-cols-2">
            <label>Environment<select name="mpesa_env" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"><option value="sandbox" @selected(old('mpesa_env', config('services.mpesa.env')) === 'sandbox')>Sandbox</option><option value="production" @selected(old('mpesa_env', config('services.mpesa.env')) === 'production')>Production</option></select></label>
            @foreach([['mpesa_consumer_key','Consumer key'],['mpesa_consumer_secret','Consumer secret'],['mpesa_shortcode','Business shortcode'],['mpesa_passkey','Lipa na M-Pesa passkey'],['mpesa_callback_url','Callback URL'],['mpesa_confirmation_url','Confirmation URL'],['mpesa_validation_url','Validation URL']] as [$key,$label])<label>{{ $label }}<input name="{{ $key }}" value="{{ in_array($key, ['mpesa_consumer_key','mpesa_consumer_secret','mpesa_passkey']) ? '' : old($key, config('services.mpesa.'.substr($key, 6))) }}" placeholder="{{ in_array($key, ['mpesa_consumer_key','mpesa_consumer_secret','mpesa_passkey']) && config('services.mpesa.'.substr($key, 6)) ? 'Saved - leave blank to keep' : '' }}" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"></label>@endforeach
        </div></section>
        <section class="card p-6"><h2 class="text-lg font-bold text-gray-800">Firebase and KEMIS</h2><div class="grid grid-cols-1 gap-4 md:grid-cols-2">@foreach([['firebase_server_key','Firebase server key'],['firebase_project_id','Firebase project ID'],['kemis_api_url','KEMIS API URL'],['kemis_api_key','KEMIS API key'],['kemis_school_code','KEMIS school code']] as [$key,$label])<label>{{ $label }}<input name="{{ $key }}" value="{{ in_array($key, ['firebase_server_key','kemis_api_key']) ? '' : old($key, config('services.'.(str_starts_with($key, 'firebase') ? 'firebase' : 'kemis').'.'.(str_starts_with($key, 'firebase') ? substr($key, 9) : substr($key, 6)))) }}" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"></label>@endforeach</div></section>
        <section class="card border-2 border-blue-100 p-6"><h2 class="text-lg font-bold text-gray-800">Google Drive file storage</h2><p class="mb-5 text-sm text-gray-500">Credentials are encrypted before being saved.</p><div class="grid grid-cols-1 gap-4 md:grid-cols-2"><label class="flex items-center gap-3 md:col-span-2"><input type="hidden" name="google_drive_enabled" value="0"><input name="google_drive_enabled" type="checkbox" value="1" @checked(old('google_drive_enabled', config('services.google_drive.enabled'))) class="h-5 w-5"><span class="text-sm font-semibold">Enable Google Drive storage</span></label><label class="md:col-span-2">Drive folder ID<input name="google_drive_folder_id" value="{{ old('google_drive_folder_id', config('services.google_drive.folder_id')) }}" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"></label><label class="md:col-span-2">Upload service-account JSON<input name="google_drive_credentials_file" type="file" accept=".json,application/json,text/plain" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"></label><label class="md:col-span-2">Or paste service-account JSON<textarea name="google_drive_credentials" rows="5" class="mt-1 w-full rounded-lg border px-3 py-2.5 font-mono text-xs"></textarea></label></div></section>
        <section class="card border-2 border-green-100 p-6"><h2 class="text-lg font-bold text-gray-800">Test SMS delivery</h2><p class="mb-4 text-sm text-gray-500">Save the Olympus settings first, then send one real test message to a phone you control.</p><form method="POST" action="{{ route('admin.settings.sms-test') }}" class="grid grid-cols-1 gap-4 md:grid-cols-2">@csrf<label>Test phone number<input name="test_phone" value="{{ old('test_phone') }}" placeholder="0712345678 or 254712345678" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm"></label><label class="md:col-span-2">Test message<textarea name="test_message" rows="2" maxlength="480" class="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm">{{ old('test_message', 'Kyandulu SMS test: delivery is working.') }}</textarea></label><div class="md:col-span-2"><button class="rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-semibold text-white">Send test SMS</button></div></form></section>
        <button class="rounded-lg bg-green-700 px-6 py-3 text-sm font-semibold text-white">Save all settings</button>
    </form>
</div>
@endsection
