@extends('layouts.admin')
@section('header', $newsletter->exists ? 'Edit Newsletter' : 'New Newsletter')
@section('content')
<form method="POST" action="{{ $newsletter->exists ? route('admin.newsletters.update', $newsletter) : route('admin.newsletters.store') }}" class="mx-auto max-w-4xl space-y-5">@csrf @if($newsletter->exists) @method('PUT') @endif
    <div class="flex flex-wrap items-end justify-between gap-3"><div><h2 class="text-2xl font-bold text-gray-900">{{ $newsletter->exists ? 'Edit newsletter' : 'Write newsletter' }}</h2><p class="mt-1 text-sm text-gray-500">The body accepts your own paragraphs exactly as written.</p></div><div class="flex gap-2">@if($newsletter->exists)<a target="_blank" href="{{ route('admin.newsletters.print', $newsletter) }}" class="rounded-lg border border-green-300 px-4 py-2.5 text-sm font-semibold text-green-800">Print preview</a>@endif<button class="rounded-lg bg-green-700 px-4 py-2.5 text-sm font-semibold text-white">Save newsletter</button></div></div>
    @if(session('success'))<div class="rounded-lg bg-green-50 p-3 text-sm text-green-800">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-lg bg-red-50 p-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
    <section class="grid gap-4 rounded-xl bg-white p-6 shadow-sm md:grid-cols-2"><label>Date<input required type="date" name="issued_on" value="{{ old('issued_on', $newsletter->issued_on?->format('Y-m-d')) }}" class="mt-1 w-full rounded border px-3 py-2"></label><label>Reference<input name="reference" value="{{ old('reference', $newsletter->reference) }}" placeholder="Ref: SCHOOL/TERM 1/2026" class="mt-1 w-full rounded border px-3 py-2"></label><label class="md:col-span-2">Salutation<input required name="salutation" value="{{ old('salutation', $newsletter->salutation) }}" class="mt-1 w-full rounded border px-3 py-2"></label><label class="md:col-span-2">RE: Subject<input required name="subject" value="{{ old('subject', $newsletter->subject) }}" placeholder="TERM 1 HALF-TERM BREAK" class="mt-1 w-full rounded border px-3 py-2"></label><label class="md:col-span-2">Newsletter body<textarea required name="body" rows="14" class="mt-1 w-full rounded border px-3 py-2" placeholder="Write the full message to parents/guardians here. Separate paragraphs with a blank line.">{{ old('body', $newsletter->body) }}</textarea></label><label>Closing<input name="closing" value="{{ old('closing', $newsletter->closing) }}" placeholder="Yours faithfully," class="mt-1 w-full rounded border px-3 py-2"></label><label>Signatory name<input name="signatory_name" value="{{ old('signatory_name', $newsletter->signatory_name) }}" class="mt-1 w-full rounded border px-3 py-2"></label><label>Signatory title<input name="signatory_title" value="{{ old('signatory_title', $newsletter->signatory_title) }}" placeholder="HEADTEACHER" class="mt-1 w-full rounded border px-3 py-2"></label><label>Copy recipients (one per line)<textarea name="copies_text" rows="4" class="mt-1 w-full rounded border px-3 py-2" placeholder="SCDE ...">{{ old('copies_text', implode("\n", $newsletter->copies ?? [])) }}</textarea></label></section>
</form>
@endsection
