@extends('layouts.admin')
@section('header', 'School Newsletters')
@section('content')
<div class="mx-auto max-w-6xl space-y-5">
    <div class="flex flex-wrap items-end justify-between gap-3"><div><h2 class="text-2xl font-bold text-gray-900">School newsletters</h2><p class="mt-1 text-sm text-gray-500">Write, save and print official communications using your school letterhead.</p></div><a href="{{ route('admin.newsletters.create') }}" class="rounded-lg bg-green-700 px-4 py-2.5 text-sm font-semibold text-white">+ New newsletter</a></div>
    @if(session('success'))<div class="rounded-lg bg-green-50 p-3 text-sm text-green-800">{{ session('success') }}</div>@endif
    <section class="overflow-hidden rounded-xl bg-white shadow-sm"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th class="px-5 py-3">Date</th><th class="px-5 py-3">Reference</th><th class="px-5 py-3">Subject</th><th class="px-5 py-3">Portal status</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($newsletters as $newsletter)<tr><td class="px-5 py-4">{{ $newsletter->issued_on?->format('d M Y') }}</td><td class="px-5 py-4 font-medium">{{ $newsletter->reference ?: '—' }}</td><td class="px-5 py-4">{{ $newsletter->subject }}</td><td class="px-5 py-4"><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $newsletter->is_published ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-600' }}">{{ $newsletter->is_published ? 'Published' : 'Draft' }}</span></td><td class="flex justify-end gap-3 px-5 py-4"><a href="{{ route('admin.newsletters.edit', $newsletter) }}" class="text-green-700">Edit</a><a target="_blank" href="{{ route('admin.newsletters.print', $newsletter) }}" class="text-blue-700">Print</a><form method="POST" action="{{ $newsletter->is_published ? route('admin.newsletters.unpublish', $newsletter) : route('admin.newsletters.publish', $newsletter) }}">@csrf<button class="{{ $newsletter->is_published ? 'text-amber-700' : 'text-green-700' }}">{{ $newsletter->is_published ? 'Unpublish' : 'Publish' }}</button></form><form method="POST" action="{{ route('admin.newsletters.destroy', $newsletter) }}">@csrf @method('DELETE')<button onclick="return confirm('Delete this newsletter?')" class="text-red-700">Delete</button></form></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-gray-500">No newsletters saved yet.</td></tr>@endforelse</tbody></table></section>
    {{ $newsletters->links() }}
</div>
@endsection
