@extends('layouts.legal', ['title' => 'Terms and Conditions'])

@section('content')
<article class="space-y-6 rounded-xl bg-white p-6 shadow-sm md:p-10">
    <div><p class="text-sm font-semibold uppercase tracking-wide text-green-700">Version {{ config('legal.version') }}</p><h1 class="mt-2 text-3xl font-bold">Terms and Conditions</h1><p class="mt-2 text-sm text-gray-500">Effective {{ now()->format('d F Y') }}</p></div>
    <p>These Terms and Conditions govern use of the {{ config('school.name') }} school management system (the "System"). By using the System, you agree to follow these terms on behalf of yourself and, where applicable, the school or organisation that authorised your account.</p>
    <section><h2 class="text-xl font-bold">1. Authorised use</h2><p class="mt-2">The System is provided for legitimate school administration, teaching, learner records, assessments, examinations, finance, communication, reporting, and related operational purposes. You must use only the account and information assigned to you.</p></section>
    <section><h2 class="text-xl font-bold">2. Account security</h2><p class="mt-2">Keep your password and sign-in details confidential. Do not share accounts, impersonate another user, bypass permissions, or attempt to access records outside your assigned role, school, class, or subject. Report suspected unauthorised access promptly to the school administrator.</p></section>
    <section><h2 class="text-xl font-bold">3. Accurate records</h2><p class="mt-2">Users must enter information accurately, use the correct academic year and current term, and correct errors through the approved workflow. Published examination results and official documents must not be altered outside the System's authorised review process.</p></section>
    <section><h2 class="text-xl font-bold">4. Documents and integrations</h2><p class="mt-2">Generated reports, merit lists, backups, SMS services, Google Drive, and other integrations are used only for authorised school purposes. External providers may have their own terms and availability limits. Do not upload confidential information to an unapproved external service.</p></section>
    <section><h2 class="text-xl font-bold">5. Availability and changes</h2><p class="mt-2">The school may restrict access for maintenance, security, legal, or operational reasons. Features, permissions, and these terms may be updated. When a material legal version changes, users must accept the new version before continuing.</p></section>
    <section><h2 class="text-xl font-bold">6. Prohibited conduct</h2><p class="mt-2">Do not misuse the System, introduce malicious code, scrape or copy records without authority, interfere with availability, disclose learner information improperly, or use the System for unlawful discrimination, harassment, fraud, or unauthorised commercial activity.</p></section>
    <section><h2 class="text-xl font-bold">7. Responsibility</h2><p class="mt-2">The school is responsible for assigning roles and reviewing records. Each user is responsible for activity performed through their account. Nothing in these terms removes rights or responsibilities that cannot legally be excluded under applicable Kenyan law.</p></section>
    <section><h2 class="text-xl font-bold">8. Contact</h2><p class="mt-2">For questions, corrections, access requests, or suspected misuse, contact the school's authorised administrator using the contact details published in the System.</p></section>
    <p class="border-t pt-5 text-sm text-gray-500">If you do not agree, do not use the System and contact the school administrator to close or review your account.</p>
</article>
@endsection
