@extends('layouts.student')
@section('header', 'My Timetable')
@section('content')
<div class="mx-auto max-w-6xl space-y-5">
    <div><p class="text-sm font-semibold uppercase tracking-wide text-emerald-700">{{ $learner->schoolClass?->name }}</p><h2 class="mt-1 text-2xl font-bold text-gray-900">Published class timetable</h2><p class="text-sm text-gray-500">Academic year {{ config('school.academic_year') }} · Term {{ config('school.current_term') }}. Only your class's published lessons are shown.</p></div>
    <div class="overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-[760px] w-full border-collapse text-sm"><thead><tr class="bg-emerald-700 text-white"><th class="border border-emerald-800 p-3 text-left">Time</th>@foreach($days as $day)<th class="border border-emerald-800 p-3 text-left">{{ ucfirst($day) }}</th>@endforeach</tr></thead><tbody>@forelse($blocks as $block)@if($block['is_break'])<tr class="bg-amber-50 text-amber-900"><th class="border p-3 text-left">{{ $block['start'] }}–{{ $block['end'] }}</th><td colspan="5" class="border p-3 text-center font-semibold">{{ $block['label'] }}</td></tr>@else<tr><th class="border bg-gray-50 p-3 text-left font-medium">{{ $block['start'] }}–{{ $block['end'] }}</th>@foreach($days as $day)@php($slot = $slots->get($day.'|'.$block['start']))<td class="border p-3 align-top">@if($slot)<div class="font-semibold text-gray-900">{{ $slot->learningArea?->name }}</div><div class="mt-1 text-xs text-gray-600">{{ $slot->teacher?->full_name }}</div>@if($slot->venue)<div class="text-xs text-gray-500">{{ $slot->venue }}</div>@endif @else<span class="text-gray-300">—</span>@endif</td>@endforeach</tr>@endif @empty<tr><td colspan="6" class="p-10 text-center text-gray-500">No published timetable is available for your class yet.</td></tr>@endforelse</tbody></table></div>
    @if($slots->isEmpty())<p class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Your school has not published a timetable for this term yet.</p>@endif
</div>
@endsection
