<div class="mx-auto max-w-5xl space-y-6">
    <div><p class="text-sm font-semibold uppercase tracking-widest text-indigo-600">ElimuHub platform control</p><h1 class="text-2xl font-bold text-gray-900">Global platform settings</h1><p class="mt-1 text-sm text-gray-600">These apply to the shared login, subscriptions and platform SMS service. They never overwrite an individual school's name, parent-fee M-Pesa account, or school settings.</p></div>
    @if(session('success'))<div class="rounded-lg border border-green-200 bg-green-50 p-4 text-sm text-green-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
    <form wire:submit="save" class="space-y-6">
        <section class="card p-6"><h2 class="text-lg font-bold text-gray-900">Login page &amp; platform identity</h2><p class="mt-1 text-sm text-gray-500">Changes appear on the shared login page after saving.</p><div class="mt-5 grid gap-4 md:grid-cols-2"><label>Platform name<input wire:model="platformName" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label><label>Login tagline<input wire:model="platformTagline" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label><label>Login footer<input wire:model="platformFooter" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label><label>Support email<input wire:model="supportEmail" type="email" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label><label>Support phone<input wire:model="supportPhone" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label><label class="md:col-span-2">Shared login logo <span class="text-xs text-gray-500">(PNG, JPG or WebP, max 2 MB)</span><input wire:model="loginLogo" type="file" accept="image/png,image/jpeg,image/webp" class="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm">@if(config('platform.logo_data'))<img src="{{ config('platform.logo_data') }}" alt="Current login logo" class="mt-3 h-20 w-20 rounded-lg border bg-white object-contain p-1">@endif @error('loginLogo')<span class="text-xs text-red-600">{{ $message }}</span>@enderror</label></div></section>
        <section class="card border border-amber-200 p-6"><h2 class="text-lg font-bold text-gray-900">Platform SMS gateway</h2><p class="mt-1 text-sm text-gray-500">One provider account used by ElimuHub. Schools can only use paid, super-admin-allocated units; provider credentials are never visible to schools.</p><div class="mt-5 grid gap-4 md:grid-cols-2"><label class="md:col-span-2">Olympus API URL<input wire:model="smsApiUrl" placeholder="https://sms.ots.co.ke" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label><label>Sender ID<input wire:model="smsSenderId" maxlength="11" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label><label>API token <span class="text-xs text-gray-500">(leave blank to retain saved token)</span><input wire:model="smsApiToken" type="password" autocomplete="new-password" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label></div></section>
        <section class="card border border-green-200 p-6"><h2 class="text-lg font-bold text-gray-900">Subscription M-Pesa API</h2><p class="mt-1 text-sm text-gray-500">This is ElimuHub's subscription collection account—separate from each school's parent-fee M-Pesa account. The callback URL must be your public Railway callback address.</p><div class="mt-5 grid gap-4 md:grid-cols-2"><label>Environment<select wire:model="mpesaEnvironment" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"><option value="sandbox">Sandbox</option><option value="production">Production</option></select></label><label>Business shortcode<input wire:model="mpesaShortcode" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label><label>Consumer key <span class="text-xs text-gray-500">(blank keeps saved)</span><input wire:model="mpesaConsumerKey" type="password" autocomplete="new-password" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label><label>Consumer secret <span class="text-xs text-gray-500">(blank keeps saved)</span><input wire:model="mpesaConsumerSecret" type="password" autocomplete="new-password" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label><label>Passkey <span class="text-xs text-gray-500">(blank keeps saved)</span><input wire:model="mpesaPasskey" type="password" autocomplete="new-password" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label><label>Public callback URL<input wire:model="mpesaCallbackUrl" type="url" class="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label></div></section>
        <button class="rounded-lg bg-indigo-700 px-6 py-3 text-sm font-semibold text-white hover:bg-indigo-800">Save global settings</button>
    </form>
</div>
