<div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start">
        <div><h1 class="text-2xl font-bold text-gray-900">SMS Control Center</h1><p class="mt-1 text-sm text-gray-600">One platform Olympus account, auditable school wallets, purchases and delivery activity.</p></div>
        <div class="flex gap-2"><a href="{{ route('admin.platform-settings.index') }}" class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Provider settings</a><button wire:click="refreshCapacity" wire:loading.attr="disabled" class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Refresh live capacity</button></div>
    </div>
    @if($notice)<div class="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-900">{{ $notice }}</div>@endif
    @if($error)<div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-900">{{ $error }}</div>@endif

    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <section class="rounded-xl border border-blue-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-blue-700">Olympus balance</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ number_format($summary['provider_balance']) }} <span class="text-sm font-medium">SMS</span></p><p class="mt-2 text-xs text-gray-500">{{ $summary['checked_at'] ? 'Checked '.\Illuminate\Support\Carbon::parse($summary['checked_at'])->format('d M Y, H:i') : 'Refresh to check live balance' }}</p></section>
        <section class="rounded-xl border border-green-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-green-700">Allocated to schools</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ number_format($summary['allocated']) }} <span class="text-sm font-medium">SMS</span></p><p class="mt-2 text-xs text-gray-500">Current total across school wallets</p></section>
        <section class="rounded-xl border border-violet-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-violet-700">Available capacity</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ number_format($summary['available']) }} <span class="text-sm font-medium">SMS</span></p><p class="mt-2 text-xs text-gray-500">Not yet allocated to a school</p></section>
        <section class="rounded-xl border {{ $summary['held_orders'] ? 'border-amber-300 bg-amber-50' : 'border-gray-200 bg-white' }} p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-amber-700">Paid orders awaiting allocation</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ number_format($summary['held']) }} <span class="text-sm font-medium">SMS</span></p><p class="mt-2 text-xs text-gray-600">{{ $summary['held_orders'] }} order(s){{ $summary['shortfall'] ? ' · shortfall '.number_format($summary['shortfall']) : '' }}</p></section>
    </div>

    @if($summary['held_orders'])<section class="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><strong>Capacity action required.</strong> Paid school orders remain held until the live Olympus balance has enough unallocated units. The refresh action checks Olympus and allocates eligible paid orders; it never creates credits artificially.</section>@endif

    <div class="grid gap-6 xl:grid-cols-3">
        <section class="overflow-hidden rounded-xl bg-white shadow-sm xl:col-span-2"><div class="border-b px-5 py-4"><h2 class="font-bold text-gray-900">Recent school SMS orders</h2><p class="text-sm text-gray-500">M-Pesa-confirmed orders are only credited after central capacity is available.</p></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">School</th><th class="px-4 py-3">Units</th><th class="px-4 py-3">Amount</th><th class="px-4 py-3">Payment</th><th class="px-4 py-3">Allocation</th></tr></thead><tbody class="divide-y">@forelse($orders as $order)<tr><td class="px-4 py-3 font-medium">{{ $order->school?->name ?? 'Removed school' }}</td><td class="px-4 py-3">{{ number_format($order->units) }}</td><td class="px-4 py-3">KSh {{ number_format((float)$order->amount, 2) }}</td><td class="px-4 py-3">{{ $order->mpesa_receipt_number ?: 'Awaiting payment' }}</td><td class="px-4 py-3"><span class="rounded-full px-2 py-1 text-xs {{ $order->status === 'confirmed' ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800' }}">{{ str_replace('_', ' ', ucfirst($order->status)) }}</span></td></tr>@empty<tr><td colspan="5" class="px-4 py-8 text-center text-gray-500">No school SMS orders yet.</td></tr>@endforelse</tbody></table></div></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-bold text-gray-900">Top school wallets</h2><div class="mt-4 space-y-3">@forelse($wallets as $school)<div class="flex items-center justify-between gap-3"><span class="truncate text-sm text-gray-700">{{ $school->name }}</span><strong class="whitespace-nowrap text-sm text-blue-700">{{ number_format($school->sms_credits) }} SMS</strong></div>@empty<p class="text-sm text-gray-500">No schools are registered.</p>@endforelse</div></section>
    </div>

    <div class="grid gap-6 md:grid-cols-2"><section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-bold text-gray-900">SMS usage — last 7 days</h2><div class="mt-4 space-y-2">@forelse($dailyUsage as $day)<div class="flex justify-between text-sm"><span>{{ \Illuminate\Support\Carbon::parse($day->day)->format('D, d M') }}</span><strong>{{ number_format($day->units) }} SMS used</strong></div>@empty<p class="text-sm text-gray-500">No local usage recorded in the last seven days.</p>@endforelse</div></section><section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-bold text-gray-900">Today’s delivery records</h2><div class="mt-4 grid grid-cols-2 gap-3 text-sm">@forelse($delivery as $status => $total)<div class="rounded-lg bg-gray-50 p-3"><p class="capitalize text-gray-500">{{ $status }}</p><p class="mt-1 text-xl font-bold text-gray-900">{{ number_format($total) }}</p></div>@empty<p class="text-gray-500">No SMS delivery records today.</p>@endforelse</div></section></div>
</div>
