<div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div><p class="text-sm font-semibold uppercase tracking-widest text-indigo-600">ElimuHub platform</p><h1 class="text-2xl font-bold text-gray-900">Super Admin Command Centre</h1><p class="mt-1 text-sm text-gray-600">Network-wide operations only. School learner, fee, and class records are intentionally not shown here.</p></div>
        <div class="flex flex-wrap gap-2"><a href="{{ route('admin.schools.index') }}" class="rounded-lg bg-indigo-700 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-800">Manage schools</a><a href="{{ route('admin.system-logs.index') }}" class="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">View audit logs</a></div>
    </div>

    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <section class="rounded-xl bg-indigo-700 p-5 text-white shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-indigo-100">Registered schools</p><p class="mt-2 text-3xl font-bold">{{ number_format($totalSchools) }}</p><p class="mt-1 text-sm text-indigo-100">{{ $activeSchools }} active · {{ $onlineSchools }} online now</p></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Subscriptions</p><p class="mt-2 text-3xl font-bold text-green-700">{{ number_format($activeSubscriptions) }}</p><p class="mt-1 text-sm {{ $expiredSubscriptions ? 'text-red-600' : 'text-gray-500' }}">{{ $expiredSubscriptions }} expired · {{ $pendingPayments }} payment(s) pending</p></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Subscription revenue</p><p class="mt-2 text-3xl font-bold text-gray-900">KSh {{ number_format($subscriptionRevenue, 0) }}</p><p class="mt-1 text-sm text-gray-500">Confirmed in the last 30 days</p></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Verified SMS payments</p><p class="mt-2 text-3xl font-bold text-amber-600">{{ number_format($verifiedSmsAllocations) }}</p><p class="mt-1 text-sm text-gray-500">Payment-backed allocations · {{ number_format($smsUsedLast30Days) }} units used in 30 days</p></section>
    </div>

    <div class="grid gap-6 lg:grid-cols-3">
        <section class="rounded-xl bg-white p-5 shadow-sm lg:col-span-2"><div class="flex items-center justify-between gap-3"><div><h2 class="font-bold text-gray-900">Registered schools</h2><p class="text-sm text-gray-500">Plans, activity, verified paid SMS units, and support access.</p></div><a href="{{ route('admin.schools.index') }}" class="text-sm font-semibold text-indigo-700 hover:underline">All schools →</a></div><div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead class="border-b text-left text-xs uppercase tracking-wide text-gray-500"><tr><th class="px-2 py-3">School</th><th class="px-2 py-3">Plan/status</th><th class="px-2 py-3">Learners</th><th class="px-2 py-3">Online users</th><th class="px-2 py-3">Paid SMS units</th><th class="px-2 py-3"></th></tr></thead><tbody class="divide-y">@forelse($schools as $school)<tr><td class="px-2 py-3"><p class="font-semibold text-gray-900">{{ $school->name }}</p><p class="text-xs text-gray-500">{{ $school->school_code ?: $school->slug }}</p></td><td class="px-2 py-3"><p>{{ $school->package?->name ?? 'No plan' }}</p><p class="text-xs {{ $school->isOnActiveSubscription() ? 'text-green-600' : 'text-red-600' }}">{{ $school->subscriptionStatusLabel() }}</p></td><td class="px-2 py-3">{{ number_format($school->active_learners_count) }}</td><td class="px-2 py-3">{{ $school->active_users_count }}</td><td class="px-2 py-3">{{ number_format($school->sms_credits) }}</td><td class="px-2 py-3"><a href="{{ route('admin.schools.index') }}" class="font-semibold text-indigo-700 hover:underline">Manage</a></td></tr>@empty<tr><td colspan="6" class="px-2 py-8 text-center text-gray-500">No registered schools yet.</td></tr>@endforelse</tbody></table></div></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-bold text-gray-900">Platform activity</h2><div class="mt-5 space-y-4"><div class="rounded-lg bg-blue-50 p-4"><p class="text-xs font-semibold uppercase tracking-wide text-blue-700">Marks ingested today</p><p class="mt-1 text-2xl font-bold text-blue-900">{{ number_format($ingestedToday) }}</p><p class="text-xs text-blue-700">Across all registered schools</p></div><a href="{{ route('admin.platform-analytics.index') }}" class="block rounded-lg border border-green-200 p-4 hover:bg-green-50"><p class="font-semibold text-green-800">Platform analytics</p><p class="mt-1 text-sm text-gray-600">Enrollment, attendance and performance by school.</p></a><a href="{{ route('admin.platform-finance.index') }}" class="block rounded-lg border border-amber-200 p-4 hover:bg-amber-50"><p class="font-semibold text-amber-800">Platform finance</p><p class="mt-1 text-sm text-gray-600">Subscription revenue and aggregated fee visibility.</p></a></div></section>
    </div>

    <div class="grid gap-6 lg:grid-cols-3">
        <section class="rounded-xl bg-white p-5 shadow-sm lg:col-span-2"><div class="flex items-center justify-between"><div><h2 class="font-bold text-gray-900">Security &amp; audit timeline</h2><p class="text-sm text-gray-500">Recent platform requests for accountability and support.</p></div><a href="{{ route('admin.system-logs.index') }}" class="text-sm font-semibold text-indigo-700 hover:underline">Full log →</a></div><div class="mt-4 space-y-3">@forelse($auditLogs as $log)<div class="flex items-start justify-between gap-3 border-b pb-3 text-sm"><div><p class="font-medium text-gray-800">{{ $log->method }} {{ $log->path }}</p><p class="text-xs text-gray-500">{{ $log->user?->name ?? 'Guest/system' }} · {{ $log->created_at?->diffForHumans() }}</p></div><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $log->status >= 400 ? 'bg-red-100 text-red-700' : 'bg-green-100 text-green-700' }}">{{ $log->status }}</span></div>@empty<p class="py-6 text-center text-sm text-gray-500">No audit entries recorded yet.</p>@endforelse</div></section>
        <section class="rounded-xl border border-indigo-100 bg-indigo-50 p-5"><h2 class="font-bold text-indigo-950">Platform controls</h2><div class="mt-4 space-y-2 text-sm"><a href="{{ route('admin.plans.index') }}" class="block rounded-lg bg-white px-3 py-3 font-semibold text-indigo-700 hover:bg-indigo-100">Plans &amp; feature access</a><a href="{{ route('admin.broadcasts.index') }}" class="block rounded-lg bg-white px-3 py-3 font-semibold text-indigo-700 hover:bg-indigo-100">Global broadcast centre</a><a href="{{ route('admin.impersonate.index') }}" class="block rounded-lg bg-white px-3 py-3 font-semibold text-indigo-700 hover:bg-indigo-100">Secure school support access</a><a href="{{ route('admin.diagnostics.index') }}" class="block rounded-lg bg-white px-3 py-3 font-semibold text-indigo-700 hover:bg-indigo-100">System diagnostics</a></div></section>
    </div>
</div>
