<div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div><p class="text-sm font-semibold uppercase tracking-widest text-indigo-600">{{ config('platform.name') }} platform</p><h1 class="text-2xl font-bold text-gray-900">Super Admin Command Centre</h1><p class="mt-1 text-sm text-gray-600">Network-wide operational totals and tenant health. Open a school only through its audited management or support tools.</p></div>
        <div class="flex flex-wrap gap-2"><a href="{{ route('admin.schools.index') }}" class="rounded-lg bg-indigo-700 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-800">Manage schools</a><a href="{{ route('admin.user-accounts.index') }}" class="rounded-lg border border-green-300 bg-green-50 px-4 py-2 text-sm font-semibold text-green-800 hover:bg-green-100">User Accounts &amp; IT Team</a><a href="{{ route('admin.support.index') }}" class="rounded-lg border border-amber-300 bg-amber-50 px-4 py-2 text-sm font-semibold text-amber-800 hover:bg-amber-100">Support queue{{ $openTickets ? ' ('.$openTickets.')' : '' }}</a><a href="{{ route('admin.system-logs.index') }}" class="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">View audit logs</a></div>
    </div>

    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <section class="rounded-xl bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Active learners</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ number_format($totalLearners) }}</p><p class="mt-1 text-sm text-gray-500">{{ number_format($newLearnersThisWeek) }} added in 7 days</p></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Teachers & staff</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ number_format($totalStaff) }}</p><p class="mt-1 text-sm text-gray-500">{{ number_format($totalTeachers) }} teaching staff</p></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Classes & subjects</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ number_format($totalClasses) }}</p><p class="mt-1 text-sm text-gray-500">{{ number_format($totalSubjects) }} active subjects · {{ number_format($totalGuardians) }} guardians</p></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Attendance today</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ $attendanceRate !== null ? $attendanceRate.'%' : '—' }}</p><p class="mt-1 text-sm text-gray-500">{{ number_format($attendanceTotal) }} entries · {{ number_format($attendanceAbsent) }} absent</p></section>
    </div>

    @if($alerts->isNotEmpty())
        <section class="rounded-xl border border-amber-200 bg-amber-50 p-5"><div class="flex items-center justify-between"><div><h2 class="font-bold text-amber-950">System alerts</h2><p class="text-sm text-amber-800">Items requiring platform attention.</p></div><a href="{{ route('admin.diagnostics.index') }}" class="text-sm font-semibold text-amber-800 hover:underline">Diagnostics →</a></div><div class="mt-4 grid gap-3 lg:grid-cols-2">@foreach($alerts as $alert)<a href="{{ route($alert['route']) }}" class="rounded-lg border border-amber-200 bg-white px-4 py-3 text-sm text-gray-800 hover:bg-amber-100">{{ $alert['text'] }}</a>@endforeach</div></section>
    @endif

    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <section class="rounded-xl bg-indigo-700 p-5 text-white shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-indigo-100">Registered schools</p><p class="mt-2 text-3xl font-bold">{{ number_format($totalSchools) }}</p><p class="mt-1 text-sm text-indigo-100">{{ $activeSchools }} active · {{ $onlineSchools }} online now</p></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Subscriptions</p><p class="mt-2 text-3xl font-bold text-green-700">{{ number_format($activeSubscriptions) }}</p><p class="mt-1 text-sm {{ $expiredSubscriptions ? 'text-red-600' : 'text-gray-500' }}">{{ $expiredSubscriptions }} expired · {{ $pendingPayments }} payment(s) pending</p></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Subscription revenue</p><p class="mt-2 text-3xl font-bold text-gray-900">KSh {{ number_format($subscriptionRevenue, 0) }}</p><p class="mt-1 text-sm text-gray-500">Confirmed in the last 30 days</p></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-gray-500">Verified SMS payments</p><p class="mt-2 text-3xl font-bold text-amber-600">{{ number_format($verifiedSmsAllocations) }}</p><p class="mt-1 text-sm text-gray-500">Payment-backed allocations · {{ number_format($smsUsedLast30Days) }} units used in 30 days</p></section>
    </div>

    <div class="grid gap-6 lg:grid-cols-3">
        <section class="rounded-xl bg-white p-5 shadow-sm lg:col-span-2"><div class="flex items-center justify-between gap-3"><div><h2 class="font-bold text-gray-900">Registered schools</h2><p class="text-sm text-gray-500">Plans, activity, verified paid SMS units, and support access.</p></div><a href="{{ route('admin.schools.index') }}" class="text-sm font-semibold text-indigo-700 hover:underline">All schools →</a></div><div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead class="border-b text-left text-xs uppercase tracking-wide text-gray-500"><tr><th class="px-2 py-3">School</th><th class="px-2 py-3">Plan/status</th><th class="px-2 py-3">Learners</th><th class="px-2 py-3">Online users</th><th class="px-2 py-3">Paid SMS units</th><th class="px-2 py-3"></th></tr></thead><tbody class="divide-y">@forelse($schools as $school)<tr><td class="px-2 py-3"><p class="font-semibold text-gray-900">{{ $school->name }}</p><p class="text-xs text-gray-500">{{ $school->school_code ?: $school->slug }}</p></td><td class="px-2 py-3"><p>{{ $school->package?->name ?? 'No plan' }}</p><p class="text-xs {{ $school->isOnActiveSubscription() ? 'text-green-600' : 'text-red-600' }}">{{ $school->subscriptionStatusLabel() }}</p></td><td class="px-2 py-3">{{ number_format($school->active_learners_count) }}</td><td class="px-2 py-3">{{ $school->active_users_count }}</td><td class="px-2 py-3">{{ number_format($school->sms_credits) }}</td><td class="px-2 py-3"><a href="{{ route('admin.schools.index') }}" class="font-semibold text-indigo-700 hover:underline">Manage</a></td></tr>@empty<tr><td colspan="6" class="px-2 py-8 text-center text-gray-500">No registered schools yet.</td></tr>@endforelse</tbody></table></div></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-bold text-gray-900">Platform activity</h2><div class="mt-5 space-y-4"><div class="rounded-lg bg-blue-50 p-4"><p class="text-xs font-semibold uppercase tracking-wide text-blue-700">Marks ingested today</p><p class="mt-1 text-2xl font-bold text-blue-900">{{ number_format($ingestedToday) }}</p><p class="text-xs text-blue-700">Across all registered schools</p></div><a href="{{ route('admin.platform-analytics.index') }}" class="block rounded-lg border border-green-200 p-4 hover:bg-green-50"><p class="font-semibold text-green-800">Platform analytics</p><p class="mt-1 text-sm text-gray-600">Enrollment, attendance and performance by school.</p></a><a href="{{ route('admin.platform-finance.index') }}" class="block rounded-lg border border-amber-200 p-4 hover:bg-amber-50"><p class="font-semibold text-amber-800">Platform finance</p><p class="mt-1 text-sm text-gray-600">Subscription revenue and aggregated fee visibility.</p></a></div></section>
    </div>

    <div class="grid gap-6 lg:grid-cols-3">
        <section class="rounded-xl bg-white p-5 shadow-sm lg:col-span-2"><div class="flex items-center justify-between"><div><h2 class="font-bold text-gray-900">Academic &amp; finance pulse</h2><p class="text-sm text-gray-500">Current aggregated school activity; individual records stay in their tenant.</p></div><div class="flex gap-3"><a href="{{ route('admin.platform-analytics.index') }}" class="text-sm font-semibold text-indigo-700 hover:underline">Analytics</a><a href="{{ route('admin.platform-finance.index') }}" class="text-sm font-semibold text-indigo-700 hover:underline">Finance</a></div></div><div class="mt-4 grid gap-4 sm:grid-cols-3"><div class="rounded-lg bg-green-50 p-4"><p class="text-xs font-semibold uppercase tracking-wide text-green-700">Fees collected today</p><p class="mt-1 text-xl font-bold text-green-900">KSh {{ number_format($feesCollectedToday, 0) }}</p></div><div class="rounded-lg bg-red-50 p-4"><p class="text-xs font-semibold uppercase tracking-wide text-red-700">Outstanding fees</p><p class="mt-1 text-xl font-bold text-red-900">KSh {{ number_format($outstandingFees, 0) }}</p></div><div class="rounded-lg bg-indigo-50 p-4"><p class="text-xs font-semibold uppercase tracking-wide text-indigo-700">Open support</p><p class="mt-1 text-xl font-bold text-indigo-900">{{ number_format($openTickets) }}</p></div></div></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-bold text-gray-900">Upcoming exams</h2><div class="mt-3 space-y-3">@forelse($upcomingExams as $exam)<div class="border-b pb-3 text-sm"><p class="font-semibold text-gray-800">{{ $exam->name }} · {{ $exam->learningArea?->name ?? 'Subject' }}</p><p class="text-xs text-gray-500">{{ $exam->school?->name ?? 'School' }} · {{ $exam->schoolClass?->name ?? $exam->grade_level }} · {{ $exam->exam_date?->format('d M') }}{{ $exam->start_time ? ' '.$exam->start_time : '' }}</p></div>@empty<p class="py-3 text-sm text-gray-500">No exams scheduled in the next 14 days.</p>@endforelse</div></section>
    </div>

    <div class="grid gap-6 lg:grid-cols-3">
        <section class="rounded-xl bg-white p-5 shadow-sm lg:col-span-2"><div class="flex items-center justify-between"><div><h2 class="font-bold text-gray-900">Security &amp; audit timeline</h2><p class="text-sm text-gray-500">Recent platform requests for accountability and support.</p></div><a href="{{ route('admin.system-logs.index') }}" class="text-sm font-semibold text-indigo-700 hover:underline">Full log →</a></div><div class="mt-4 space-y-3">@forelse($auditLogs as $log)<div class="flex items-start justify-between gap-3 border-b pb-3 text-sm"><div><p class="font-medium text-gray-800">{{ $log->method }} {{ $log->path }}</p><p class="text-xs text-gray-500">{{ $log->user?->name ?? 'Guest/system' }} · {{ $log->created_at?->diffForHumans() }}</p></div><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $log->status >= 400 ? 'bg-red-100 text-red-700' : 'bg-green-100 text-green-700' }}">{{ $log->status }}</span></div>@empty<p class="py-6 text-center text-sm text-gray-500">No audit entries recorded yet.</p>@endforelse</div></section>
        <section class="rounded-xl border border-indigo-100 bg-indigo-50 p-5"><h2 class="font-bold text-indigo-950">Platform controls</h2><div class="mt-4 space-y-2 text-sm"><a href="{{ route('admin.user-accounts.index') }}" class="block rounded-lg bg-green-700 px-3 py-3 font-semibold text-white hover:bg-green-800">User Accounts &amp; IT Team <span class="float-right text-xs font-normal">Create IT Team accounts →</span></a><a href="{{ route('admin.platform-settings.index') }}" class="block rounded-lg bg-white px-3 py-3 font-semibold text-indigo-700 hover:bg-indigo-100">Global settings &amp; APIs</a><a href="{{ route('admin.plans.index') }}" class="block rounded-lg bg-white px-3 py-3 font-semibold text-indigo-700 hover:bg-indigo-100">Plans &amp; feature access</a><a href="{{ route('admin.broadcasts.index') }}" class="block rounded-lg bg-white px-3 py-3 font-semibold text-indigo-700 hover:bg-indigo-100">Global broadcast centre</a><a href="{{ route('admin.support.index') }}" class="block rounded-lg bg-white px-3 py-3 font-semibold text-indigo-700 hover:bg-indigo-100">Support tickets @if($openTickets)<span class="float-right rounded-full bg-amber-100 px-2 py-0.5 text-xs text-amber-800">{{ $openTickets }}</span>@endif</a><a href="{{ route('admin.impersonate.index') }}" class="block rounded-lg bg-white px-3 py-3 font-semibold text-indigo-700 hover:bg-indigo-100">Secure school support access</a><a href="{{ route('admin.platform-maintenance.index') }}" class="block rounded-lg bg-white px-3 py-3 font-semibold text-indigo-700 hover:bg-indigo-100">Maintenance mode</a><a href="{{ route('admin.diagnostics.index') }}" class="block rounded-lg bg-white px-3 py-3 font-semibold text-indigo-700 hover:bg-indigo-100">System diagnostics</a></div></section>
    </div>
</div>
