<?php
namespace App\Http\Controllers;
use App\Models\PastExamDocument; use App\Models\SchoolClass; use App\Services\GoogleDriveStorage; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str;
class PastExamDocumentController extends Controller {
 public function index(Request $request) { $documents=PastExamDocument::with(['schoolClass','uploader'])->when($request->type,fn($q,$v)=>$q->where('document_type',$v))->latest()->paginate(20); return view('admin.exams.archive',['documents'=>$documents,'classes'=>SchoolClass::orderBy('name')->get()]); }
 public function store(Request $request, GoogleDriveStorage $storage) { abort_unless($request->user()->can('manage exams') && $request->user()->school_id,403); $data=$request->validate(['title'=>'required|string|max:255','document_type'=>'required|in:past_exam,merit_list,report_cards','academic_year'=>'nullable|string|max:9','term'=>'nullable|string|max:20','class_id'=>'nullable|exists:school_classes,id','document'=>'required|file|mimes:pdf|max:5120']); if ($data['class_id'] && !SchoolClass::whereKey($data['class_id'])->exists()) abort(403); try { $file=$request->file('document'); $name=Str::uuid().'.pdf'; $path=$storage->store($file,'exam-archive/'.now()->format('Y/m'),$name,'application/pdf'); unset($data['document']); PastExamDocument::create([...$data,'school_id'=>$request->user()->school_id,'file_path'=>$path,'original_name'=>$file->getClientOriginalName(),'file_size'=>$file->getSize() ?: 0,'uploaded_by'=>$request->user()->id]); return back()->with('success','PDF archived for this school.'); } catch (\Throwable $exception) { report($exception); return back()->withErrors(['document' => 'The PDF could not be archived: '.$exception->getMessage()])->withInput(); } }
 public function show(PastExamDocument $document, GoogleDriveStorage $storage) { abort_unless(auth()->user()->can('view exams'),403); $contents=str_starts_with($document->file_path,'private:') ? Storage::disk('local')->get(substr($document->file_path,8)) : $storage->contents($document->file_path); return response($contents,200,['Content-Type'=>'application/pdf','Content-Disposition'=>'inline; filename="'.addslashes($document->original_name).'"']); }
 public function destroy(PastExamDocument $document, GoogleDriveStorage $storage) { abort_unless(auth()->user()->can('manage exams'),403); if (str_starts_with($document->file_path,'private:')) Storage::disk('local')->delete(substr($document->file_path,8)); else $storage->delete($document->file_path); $document->delete(); return back()->with('success','Archived PDF deleted.'); }
}
